### ISSUE TITLE
use exhaustive match statement in `peer/connection.rs`

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#1027]
based on a comment in code review

---

do we want to try to find a way to get exhaustive matching here?

_Originally posted by @yaahc in https://github.com/ZcashFoundation/zebra/pull/1016#discussion_r483852626_

**Comment by hdevalence** [comment]
The relevant part of `connection.rs` is in `handle_message_as_request`, which is responsible for interpreting a Bitcoin message as a `Request` from a remote peer, then passing it to our inbound network service.

Ideally, this function should be handled as a single `match` statement, where each match arm is independent of the others and handles exactly one pattern.  This can make the code superficially uglier, e.g.,
```rust
            Message::GetData(items)
                if items
                    .iter()
                    .all(|item| matches!(item, InventoryHash::Tx(_))) => { /* ... */ }
```
but makes the code easier to analyze and change (because the match arms are more independent of each other, and each one does one thing.

Currently there are three match statements in a row, with `_` wildcard cases.  Ideally they would be combined into one match statement, with no wildcard cases.  Initially, this will probably require adding a bunch of patterns whose bodies are like
```rust
Message::Foo => {
    tracing::debug!("unhandled message type Foo");
    None
}
```
but it will be useful to enumerate all of the messages we need to be able to handle, rather than having a single catch-all "unhandled" arm.
