### ISSUE TITLE
Remove "TODO: Error=Report" and similar comments

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1034]
We are currently using the `Report` error type where it is supported.

The remaining error types need to be `Clone`, because they are sent through a `Buffer` or `Batch` service wrapper.

So we can remove the remaining TODO comments.

For details, see https://github.com/ZcashFoundation/zebra/pull/1012#discussion_r485170342

**Comment by teor2345** [comment]
Currently blocked by #1012 and possibly #1009.

**Comment by yaahc** [comment]
> The remaining error types need to be Clone, because they are sent through a Buffer or Batch service wrapper.

To be precise, the remaining error types don't need to be clone, they just need to be `Into<Box<dyn Error + ...>>` because tower-buffer and tower-batch rely on the `Error` interface + `Arc` to make existing errors clonable at the cost of mutability. The goal before was to replace `Box<dyn Error>` with `Report` but `Report` needs to be mutable to have extra context added to reports as its propagated throughout the program. If we wrapped it in an arc and converted that back into a Box<dyn Error> like `tower-buffer` does we'd be unable to use the Report as we wanted to, since its now type erased and hidden from us, and this could only be avoided if `Report` itself were `Clone` which is more or less impossible given its API.

**Comment by hdevalence** [comment]
It seems simplest to use `type BoxError = Box<dyn std::error::Error + Send + Sync + 'static>` for `Service` implementations, because it's the same error type produced by other `tower` middleware and it works well with generic bounds.

**Comment by mpguerra** [comment]
> Currently blocked by #1012 and possibly #1009.

Seems both of those are already merged, will remove blocked label

**Comment by teor2345** [comment]
Most of these got done.
