### ISSUE TITLE
Put a shorter time limit on Zebra CI jobs

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1142]
**Version**

Current Zebra main branch.

**Platform**

All CI platforms.

**Description**

The existing CI time limits are way too high. They make it difficult to diagnose and fix CI-only hangs, because test output isn't available until the tests finish.

As an example, see this macOS CI run: https://github.com/ZcashFoundation/zebra/pull/1053/checks?check_run_id=1233819386

It appears to have hung during the tests - it is still running 100 minutes later.

**Suggested Fixes**

- [x] Put a time limit of 30 minutes on every CI job, using the CI config or `timelimit` command
- [ ] Configure CI to show live logs, rather than waiting for each stage to finish (if possible)

**Comment by dconnolly** [comment]
> Configure CI to show live logs, rather than waiting for each stage to finish (if possible)

For in-GitHub Actions jobs, they are pretty live. For the Google Cloud Build job, because we want to support external fork PRs, we have to do them via the installed GitHub App to trigger them, and that doesn't support live logs :(. The jobs that run as a GitHub Action do support live logs from gcloud, but because external forks don't get access to our GCLOUD_SECRET, we can't run them at all on those external fork PRs. :/

**Comment by dconnolly** [comment]
> Put a time limit of 30 minutes on every CI job, using the CI config or timelimit command

The Google Cloud Build is configured to end at 30 minutes, I can update each GH Actions job/step to timeout at 30 minutes.
