### ISSUE TITLE
Dedupe Verification error types (Block, Chain)

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#1186]
> Hmm, it looks like the error type duplication is pre-existing to this PR: there's VerifyBlockError and VerifyTransactionError that both shouldn't exist. We could either fix it now, or in a later PR. The downside of fixing it later is that implementing other consensus rules requires having the right error types, so all later changes would still block on the later PR.

Comes out of https://github.com/ZcashFoundation/zebra/pull/1173

1. VerifyBlockError -> BlockError
2. VerifyChainError -> (new) ChainError
3. Distinguish timeouts by wrapping `Elapsed` in different errors, depending on where it comes from
4. Fix the downcast from BoxError to redjubjub::Error at `zebra-consensus/src/error.rs:76`
    - Remove the InternalDowncastError type
    - Remove as many BoxErrors as possible

**Comment by teor2345** [comment]
Moved into the first alpha because it's causing a panic, see #1357 for details.

**Comment by conradoplg** [comment]
A related issue is discussed [here](https://github.com/ZcashFoundation/zebra/pull/2679#issuecomment-907943652). Basically the script verifier can timeout, which returns a `use tower::timeout::error::Elapsed` error. This is converted to a `TransactionError` (since that's the error type of the transaction verifier service), and since there's no matching enum item, it ends up being converted to `InternalDowncastError`.

I'm not sure what's the best approach for this. 

- Create a `Elapsed` error in `TransactionError`? (Would solve this specific case, but there may be others)
- Try to remove the `BoxError` -> `TransactionError` conversion by using `TransactionError` instead of `BoxError` where applicable (e.g. `AsyncChecks`)?
- Or just leave as is?

**Comment by teor2345** [comment]
> * Create a `Elapsed` error in `TransactionError`? (Would solve this specific case, but there may be others)

I think we might want a different error variant for each different kind of timeout, so we know what has timed out.

> * Try to remove the `BoxError` -> `TransactionError` conversion by using `TransactionError` instead of `BoxError` where applicable (e.g. `AsyncChecks`)?

I'd like to replace `BoxError` with enum error types as much as possible.

But we'll still need it in some places, because some types and traits require `BoxError` (like `ServiceExt::oneshot`, and maybe `tower::Buffer`?).

**Comment by teor2345** [comment]
This isn't particularly important.
