### ISSUE TITLE
Choose one of stable or nightly clippy.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1212]
**Description**

Currently, our CI runs both stable and nightly clippy. This means that it can be hard to pre-check code, because the local clippy may not match the CI.  In addition, new lints are sometimes added to nightly clippy.  This can cause a frustrating experience, where some code fails the clippy pass for an unrelated reason, or for a reason that couldn't be checked in advance.  In addition, it means that we duplicate work for the CI server.

Instead, I think we should pick one or the other of stable or nightly.

**Comment by teor2345** [comment]
I think we should pick stable clippy, because:
* nightly clippy changes often
* nightly clippy lints are sometimes removed or revised
* we can't guarantee that developers will have the latest version of nightly clippy installed - but CI always uses the latest

If we pick stable clippy, then all developers should also use stable clippy locally. (For efficiency reasons, this probably also means using stable rustc for builds.)

If they decide to use nightly, they'll need to fix or ignore any nightly clippy bugs themselves.

**Comment by dconnolly** [comment]
I'd go with Clippy on stable

**Comment by teor2345** [comment]
When we try to ignore new nightly clippy lints, stable clippy complains about unknown lint names:
```
error: unknown clippy lint: clippy::from_iter_instead_of_collect
 --> zebra-test/src/lib.rs:3:10
  |
3 | #![allow(clippy::from_iter_instead_of_collect)]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `-D clippy::unknown-clippy-lints` implied by `-D warnings`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unknown_clippy_lints
```
https://github.com/ZcashFoundation/zebra/pull/1303/checks?check_run_id=1404428631#step:4:1324

So we really do need to choose one or the other.

**Comment by hdevalence** [comment]
I removed nightly clippy in #1358 because I ran into this problem again
