### ISSUE TITLE
Check how zcashd handles missing blocks?

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1307]
## Task

When Zebra's inbound service answers a BlocksByHash, if any of those blocks aren't in Zebra's best chain, it errors and drops the entire request.

We need to check if zcashd returns partial responses instead.

Once we've resolved this ticket, we should remove or update the corresponding TODO comment:
https://github.com/ZcashFoundation/zebra/blob/main/zebrad/src/components/inbound.rs#L145

**Comment by teor2345** [comment]
@hdevalence do you think we need to do this task in the first alpha release?

**Comment by mpguerra** [comment]
I'm going to move this off the First Alpha Release milestone. 

As far as I can tell this doesn't affect the actual sync. Although it might mean we're not exactly a well behaving node by dropping the request, it seems like a reasonable enough action that would not otherwise adversely affect the network.

**Comment by daira** [comment]
This is not ideal, but I don't think it will cause any harm to the network.

**Comment by teor2345** [comment]
`zcashd` ignores missing blocks, but returns `notfound` for missing transactions:
https://github.com/zcash/zcash/blob/e7b425298f6d9a54810cb7183f00be547e4d9415/src/main.cpp#L5517

This means our block state machine needs to be modified.
