### ISSUE TITLE
Create function for post-blossom height adjustments

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#1311]
**Is your feature request related to a problem? Please describe.**

> It feels like we do post-blossom height adjustments in a few different parts of the code.
>
> Is there a way to abstract them into a new function?

https://github.com/ZcashFoundation/zebra/pull/1170#discussion_r508879222

**Describe the solution you'd like**

Create a function that can be used from at least 2 places.

**Describe alternatives you've considered**

Leave it as it is.

**Additional context**

https://github.com/ZcashFoundation/zebra/pull/1170

This is not an urgent task.

**Comment by oxarbitrage** [comment]
The problem i see with this is that the adjustments made post post blossom are not the same in the 2 places we need to do them.

There is one adjustment we do in `halving_divisor()`:

![halving](https://user-images.githubusercontent.com/21685097/110127343-4921ea00-7da4-11eb-85ae-2af1a0cd2e1a.png)

And the other one in `founders_reward_address()`:

![foundersaddress](https://user-images.githubusercontent.com/21685097/110127407-5dfe7d80-7da4-11eb-9cd9-40b0545336af.png)

The are some differences that i cant see how to abstract:

1- The height for pre blossom is scaled in the halving calculation while the height pre blossom for the founders reward is not modified.
2- I cant find any point of coincidence in the post blossom calculations of the 2 spec points, they even use different constants. Maybe my algebra is not good enough or there is something i am not seeing.

**Comment by daira** [comment]
I would strongly suggest to follow the spec as literally as possible here. It took quite some thinking and review to get it right.

**Comment by teor2345** [comment]
If the calculations are different, they should use different functions, which should have function docs describing the differences and pointing to the relevant sections of the spec. Since the existing functions are fairly simple, you could add explanations to them.

Here are the different places that a blossom adjustment happens:
https://github.com/ZcashFoundation/zebra/pull/1170/files#diff-1e411c4dd6dc3ad59094c14b82cba0fdd4fee34f841ede1ab092d87a65ff77f9R51-R54
https://github.com/ZcashFoundation/zebra/pull/1170/files#diff-1e411c4dd6dc3ad59094c14b82cba0fdd4fee34f841ede1ab092d87a65ff77f9R71-R75
https://github.com/ZcashFoundation/zebra/blob/128643d81e357157bfb3af3725bac653abfb402e/zebra-consensus/src/block/subsidy/general.rs#L64-L68

Can you match each one with the relevant part of the spec?
(You only quoted two spec sections above, but there are 3 adjustments.)

Are there any other adjustments?

**Comment by mpguerra** [comment]
@oxarbitrage do we still need to deal with this now that we are checkpointing on canopy?

**Comment by oxarbitrage** [comment]
In my view we should not do the changes proposed here not because we are checkpointing on canopy but iirc just because is clearer to leave it as it is now as it follows the spec more closely. We can always do this if we need/want but i don't think we need an open ticket. Closing.
