### ISSUE TITLE
Add severity labels for bug reports

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1436]
**Is your feature request related to a problem? Please describe.**

We have started to receive external bug reports and we don't currently have a good way to specify their severity, in particular when triaging or attempting to prioritize multiple bug reports. 

**Describe the solution you'd like**

We should add new labels to the zebra github repo to specify the severity of a bug, e.g

- **Blocker**: zebra is unable to function on officially supported systems.
- **Critical**: Bug completely affects zebra functionality, is a security issue or can cause serious damage to the network
- **Major**: Bug partially affects zebra functionality and workarounds are cumbersome and/or impractical
- **Minor**: Bug causes undesirable behavior but does not affect overall zebra functionality, it is easy to workaround
- **Low**: Bug is barely noticeable

**Describe alternatives you've considered**

We may want to keep things simple and only have 4 severity levels (or less), e.g

- Critical
- Major
- Minor
- Low

**Additional context**

I have tried to start defining the meaning of the different severity levels when applied to zebra. We should discuss and refine this list and the exact definition and meaning for each.

**Comment by teor2345** [comment]
It's easy to confuse priority #1437 and severity (this ticket). Do we really need both?

We've been trying to follow the Rust issue labels and colours. Instead of bug severities, they have specific labels that describe the nature of the bug.

I suggest we start with these labels which are relevant to Zebra:

I-consensus 💥
Zebra breaks a consensus rule (the worst kind of bug)

I-crash
Zebra crashes

I-internal-error
Zebra panics with an internal error message

I-hang
A Zebra component stops responding to requests

I-heavy
Problems with excessive memory, disk, or CPU usage

I-slow
Problems and improvements with respect to performance

I-needs-decision
Issues in need of decision

I-nominated
Issues nominated for discussion during a team meeting

I-prioritize
Issues that need prioritization

Here is Rust's list:
https://github.com/rust-lang/rust/labels?page=9&sort=name-asc

**Comment by mpguerra** [comment]
Severity should highlight how much impact a bug has on node functionality and is something that would be assigned by the engineers as they discover and/or triage bugs. A severity label shouldn't really change over time unless we find ways to mitigate an issue.

Priority is more about timing and scheduling and something that should probably be assigned by the project manager for an issue. Priority of an item can change over time, maybe something is not very urgent at first but as a release gets closer it may become more urgent to deal with. 

Does this help to distinguish between them?

**Comment by teor2345** [comment]
> Severity should highlight how much impact a bug has on node functionality and is something that would be assigned by the engineers as they discover and/or triage bugs. A severity label shouldn't really change over time unless we find ways to mitigate an issue.
> 
> Priority is more about timing and scheduling and something that should probably be assigned by the project manager for an issue. Priority of an item can change over time, maybe something is not very urgent at first but as a release gets closer it may become more urgent to deal with.
> 
> Does this help to distinguish between them?

Thanks, that's helpful.

That also explains why the Rust project uses bug categories instead of severities. Since the severity doesn't change over time, we can categorise bugs by the specific impact they have on a node: consensus rule violation, crash, hang, panic, ...

**Comment by teor2345** [comment]
I think we decided not to do this task, @mpguerra ?
