### ISSUE TITLE
Make zebra-utils non-publishable

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#1474]
It's full of developer and end-user scripts and tools, we don't want it to get accidentally published like other zebra-* crates.

**Comment by mpguerra** [comment]
We also discussed adding a README to the zebra-utils directory during the zebra sync, do we still want to do this and, if so, shall we do it as part of this issue or create a new one?

**Comment by teor2345** [comment]
> We also discussed adding a README to the zebra-utils directory during the zebra sync, do we still want to do this and, if so, shall we do it as part of this issue or create a new one?

We want to add a README to `zebra-consensus/checkpoint` that points to the `zebra-checkpoints` tool in `zebra-utils`. I opened #1482 to do that, because the tasks aren't really connected, and they don't conflict.

We didn't really talk about adding a README to `zebra-utils` itself, but it seems like a good idea. It's related to this ticket, but it can be done separately, so I opened #1483 to do that.
