### ISSUE TITLE
check/fix ZEBRA_SKIP_NETWORK_TESTS

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#1730]
Some tests are skipped from the CI:

```
# Ubuntu runners don't have network or DNS configured during test steps
# Windows runners have an unreliable network
if: matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest'
run: echo "ZEBRA_SKIP_NETWORK_TESTS=1" >> $GITHUB_ENV
```

The comment is not true and we have a more stable zebra now. First check if it an simply be removed completely. If this is not possible check the tests that use `ZEBRA_SKIP_NETWORK_TESTS` individually and skip only the ones that will not pass. Explain why they need to be skipped.

This issue is a follow-up of https://github.com/ZcashFoundation/zebra/pull/1726

**Comment by oxarbitrage** [comment]
The comment seems to be actually true, i made several tests in https://github.com/ZcashFoundation/zebra/pull/1732 and we dont have any network capability: https://github.com/ZcashFoundation/zebra/pull/1732/checks?check_run_id=1891138982#step:6:7

It is a bit strange that in the docs they refer to ping or traceroute however other networking commands including dns resolution are not working either: https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#cloud-hosts-for-github-hosted-runners and that is our problem.

>  Inbound ICMP packets are blocked for all Azure virtual machines, so ping or traceroute commands might not work.

From the same documentation:

> GitHub hosts macOS runners in GitHub's own macOS Cloud.

This seems to be the reason of why macOS is actually working.

I think there is not much we can do than to update a bit the reason of the skipped tests in the comment.

**Comment by teor2345** [comment]
We should also explain why the other tests that run zebrad work.

Most tests only check launch behaviour (or local port binding). After those tests succeed, zebrad hangs until its network requests time out. But since the tests don't check any output past port binding, it doesn't matter whether zebrad hangs or continues.

**Comment by teor2345** [comment]
Hey @oxarbitrage, it looks like Windows CI builds are still running the large sync tests:
https://github.com/ZcashFoundation/zebra/pull/1750/checks?check_run_id=1908798434#step:8:559
https://github.com/ZcashFoundation/zebra/pull/1749/checks?check_run_id=1908787726#step:8:559

So there are a few issues with this ticket:
- [ ] Windows (and Linux) large sync tests should be disabled by the `ZEBRA_SKIP_NETWORK_TESTS` env var
  - see PR #1751 for diagnostics
- [ ] the new comments added in #1732 are wrong, because at least some Windows machines have DNS and TCP access - in the logs, the sync makes partial progress, but fails due to a timeout
  - see PR #1752 for a revert

These are all draft PRs, please feel free to edit or replace them.

I'm pretty much at the end of my day right now, but maybe @dconnolly can help you sort out these CI failures.

**Comment by teor2345** [comment]
Maybe we need powershell syntax to set Windows env vars?
https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files

**Comment by teor2345** [comment]
Or maybe we need to deploy more Zebra instances to testnet (#1222, blocked by #1709).

**Comment by oxarbitrage** [comment]
The problem here is that i did:

`if: matrix.os != 'macOS-latest'`

And this seems to skip the env var setup fully. The var will only activate when the OS is macOS. I don't know how this actually passed some tests before but anyway i think the way to go it is like we had before:

`if: matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest'`

This is done at https://github.com/ZcashFoundation/zebra/pull/1752

**Comment by oxarbitrage** [comment]
Closed by https://github.com/ZcashFoundation/zebra/pull/1752
