### ISSUE TITLE
RFC for ZIP-213: Validate Shielded Coinbase Outputs

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#2115]
**Is your feature request related to a problem? Please describe.**

ZIP-213 introduces shielded coinbase.

**Describe the solution you'd like**
 In order to implement this we should first write up the design for how  this work in an RFC. 

**Additional context**

PR #1190 started implementing this work and should be used to inform the design and write up

**Comment by mpguerra** [comment]
Moving this out of Sprint 13 as we'll deal with coinbase rules at a later date, post NU5 activation

**Comment by teor2345** [comment]
> Moving this out of Sprint 13 as we'll deal with coinbase rules at a later date, post NU5 activation

We're only skipping coinbase *input* validation: Founders Reward, Funding Streams, and Miner Rewards.
We have to validate coinbase *outputs*, because outputs get spent along with other Zcash coins.

But looking at the list of consensus rules in #608, we don't need a design here, just some good function and module docs.
