### ISSUE TITLE
Skip download and verification if the transaction is already in the mempool or state

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2708]
## Motivation

In the transaction download stream, we want to skip transactions we've already downloaded or verified.

We want to skip:
* witnessed transaction IDs (`WtxId`) that are already in the mempool
* witnessed transaction IDs (`WtxId`) that have already been rejected by the mempool
* mined transaction IDs (`transaction::Hash`) that have already been committed to the state

We need to check:
* transaction IDs before downloading
* downloaded and `PushTransaction`s before verifying

**Comment by mpguerra** [comment]
I forgot this one also needs an estimate. Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2708?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

Probably just an estimate from @conradoplg is fine since they're the one who has actually worked on it already :)
