### ISSUE TITLE
Document `mempool` at each module level with rustdoc

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2859]
## Motivation

We would like to flesh out the module-level rustdoc for everything in the `mempool` component in `zebrad`. Currently there are one or two lines in several modules and nothing for `downloads` and `storage`.  We would like to document what these modules do, how they operate, and our design thoughts behind the implementation, which will be visible in the code and in [the Zebra docs](https://doc-internal.zebra.zfnd.org/zebrad/components/mempool/index.html). 

Some tips from the `rustdoc` book on [how to write documentation](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html#documenting-components:): 

> It is recommended that each item's documentation follows this basic structure:
```
[short sentence explaining what it is]

[more detailed explanation]

[at least one code example that users can copy/paste to try it]

[even more advanced explanations if necessary]
``` 

Modules to flesh out / document:
- [x] `zebrad::commands::start` - @teor2345 
    - PR #2888
- [x] `zebrad::components::mempool` - @dconnolly
- [x] `zebrad::components::mempool::crawler` - @jvff 
    -  #2968
- [x] `zebrad::components::mempool::downloads` - @conradoplg 
    - #2879 
- [x] `zebrad::components::mempool::error` - @upbqdn 
    - #2942 
- [x] `zebrad::components::mempool::gossip` - @oxarbitrage 
    - #2884
- [x] `zebrad::components::mempool::storage` - @oxarbitrage 
    - #2884
    - #2965 
  
Types to document:
- [x] `zebrad::components::mempool::Request` - @teor2345
    - PR #2888
- [x] `zebrad::components::mempool::Response` - @teor2345
    - PR #2888

**Comment by mpguerra** [comment]
@ZcashFoundation/zebra-team can everyone please assign themselves one module and/or type to document based on who's been working on it the most? I will also go through the modules and assign someone based on commit history.

We should have individual PRs from everyone to fill in the docs rather than just have one person do them all

**Comment by mpguerra** [comment]
I've made some preliminary assignments for the documentation. 

Feel free to swap things around, the original assignee is responsible for finding an alternative person if they are not able to document the assigned module.

This issue is nice to have but low priority

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2859?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by oxarbitrage** [comment]
If we want the mempool documentation to show up in our docs website: https://doc.zebra.zfnd.org/zebrad/ we need to generate with `cargo doc --document-private-items`.

Also maybe will be good for beta to fix all the doc warnings we can. Almost all of hem are a suggestion to use automatic link feature, while there are some of not found internal link paths.

**Comment by teor2345** [comment]
> If we want the mempool documentation to show up in our docs website: https://doc.zebra.zfnd.org/zebrad/ we need to generate with `cargo doc --document-private-items`.

We already deploy private docs in our CI:
https://github.com/ZcashFoundation/zebra/blob/002c533ea8f720efeb94b62b3770deca0e6c2b6c/.github/workflows/docs.yml#L62-L64

Public items are listed at https://doc.zebra.zfnd.org/
Private items are listed at https://doc-internal.zebra.zfnd.org/

### Public Mempool Docs

We can make the mempool public, if you want it to appear on the public docs site:
https://github.com/ZcashFoundation/zebra/blob/002c533ea8f720efeb94b62b3770deca0e6c2b6c/zebrad/src/lib.rs#L39

Can you open an optional ticket for the mempool having public docs?

### Public Mempool Config Docs

We should definitely make the mempool config public:
https://github.com/ZcashFoundation/zebra/blob/002c533ea8f720efeb94b62b3770deca0e6c2b6c/zebrad/src/components/mempool.rs#L27

Because the mempool config is private, its fields aren't listed in the public docs:
https://doc.zebra.zfnd.org/zebrad/config/struct.ZebradConfig.html#structfield.mempool

Can you open a medium-priority ticket for making the mempool config public?

### Doc Warnings

> Also maybe will be good for beta to fix all the doc warnings we can. Almost all of hem are a suggestion to use automatic link feature, while there are some of not found internal link paths.

Can you open an optional ticket to fix doc warnings?

**Comment by teor2345** [comment]
I gave @dconnolly some of my extra assignments, because I need to open a bunch of bug PRs today.
(And get the transaction fee into mempool storage.)

**Comment by teor2345** [comment]
I just swapped my assignments with @dconnolly, because I'm going to edit that code right now anyway.

**Comment by mpguerra** [comment]
Going to move this to next sprint (Sprint 21) as part of the beta release with mempool
