### ISSUE TITLE
Expose proof validation for BCTV14 type

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#304]
Expose validation on our Bctv14 type. If we come across a BCTV14 proof during validation, we should panic or error. In the checkpoint verifier, we should be only checking hashes, so if we've gotten to calling down to validating the old-type proof, we've done something wrong.

https://github.com/ZcashFoundation/zebra/blob/main/zebra-chain/src/proofs/bctv14.rs

https://zips.z.cash/protocol/protocol.pdf#concretezk

**Comment by hdevalence** [comment]
For the reason described here: https://github.com/ZcashFoundation/zebra/issues/305#issuecomment-604016390 I think it doesn't make sense to have this be a method, so I don't think that there's a work item to do here.  The proof types are fixed by the transaction version enum, so we can't come across a BCTV14 proof except with an old tx version, and those will have to be rejected for other consensus reasons.
