### ISSUE TITLE
Investigate version field in block 434873

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#307]
The [Zcash specification]( https://zips.z.cash/protocol/protocol.pdf#blockheader) says that the current and only `version` field for block headers is `4`.  When trying to download and parse the chain, we fail at block 434873, due to a bad version field. Investigating with `zcash-cli` reveals a strange version field, not just a problem with our code:

```
~/c/z/zcashd (master|✔) $ ./src/zcash-cli getblock 434872 | jq '.version'
4
~/c/z/zcashd (master|✔) $ ./src/zcash-cli getblock 434873 | jq '.version'
536870912
~/c/z/zcashd (master|✔) $ ./src/zcash-cli getblock 434874 | jq '.version'
4
```

**Comment by tarcieri** [comment]
The two numbers are mirror images of each other in binary:

| Base 10 | Base 2 |
|---------|--------|
| 4 | `00000000000000000000000000000100` |
| 536870912 | `00100000000000000000000000000000` |

**Comment by hdevalence** [comment]
Interesting. I'm confused on two points:

1. What would cause bit-reversal of the field, if it wasn't intentional;

2. Why this is accepted by Zcashd.

On (2), @str4d [points out](https://twitter.com/str4d/status/1237468725747396608):

> Zcash has Bitcoin-inherited behaviour that any version >= +4 is valid. This is exactly why we can't just bump the version number to 5 with a block header change; we instead need to utilise the fact that no negative version has ever been allowed, same as we did for transactions.

**Comment by dconnolly** [comment]
> Hence, I suspect that this is from mining pool software that set version = 2 (which would usually be invalid) and used Bitcoin-Stratum endianness, which then was interpreted by Zcash-Stratum mining clients as version = 0x20000000 (which is "valid").

\- @str4d

https://twitter.com/str4d/status/1237471089942360064

**Comment by hdevalence** [comment]
There are 4,015 such blocks (up to height 756,600), all with the version field set to the bit-reversal of `2u32`.  For reference, a list of all of the blocks is available in [this gist](https://gist.github.com/hdevalence/30ce0674ce1b7d27221a975d9d2b6ef9), generated with

```fish
for i in (seq 0 756600); ./src/zcash-cli getblock $i | jq -c '[.version, .height]' | grep -v '\[4,' ; end;
```

**Comment by gtank** [comment]
The pool producing these blocks is [AntPool](https://v3.antpool.com/home) and the mechanism does seem to be the Stratum mismatch noted by @str4d. They are in violation of the Zcash protocol spec, and have been since block 434873 in November 2018.

![image (4)](https://user-images.githubusercontent.com/622063/76449592-bd4ccc00-63a2-11ea-8af1-487f01d1c678.png)

Upon investigation, it turns out that other Zcash contributors noticed this as early as May 2019. Discussion with AntPool didn't produce results, and the Zcash spec was clarified to accept these blocks while prohibiting their further production. See [7.5 Block Header](https://zips.z.cash/protocol/protocol.pdf#blockheader) for full details, excerpted here for clarity:

![image (5)](https://user-images.githubusercontent.com/622063/76449596-c2aa1680-63a2-11ea-8e96-1dc2b148ab21.png)

As a consequence, future Zcash header formats will need to use negative version numbers to distinguish themselves.
