### ISSUE TITLE
Refine JoinSplit ephemeral keys to be x25519_dalek::PublicKeys

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#313]
We're pulling in dalek elsewhere for these types too.

**Comment by dconnolly** [comment]
x25519_dalek::PublicKey does not impl `PartialEq` or `Eq`...

**Comment by hdevalence** [comment]
Do we need to have `PartialEq` for `JoinSplitDescription`s?  My sense is that in general use, it's not necessary to ever check equality, and if we need to check equality when doing property tests we could serialize as needed rather than carrying extra impls around.  At the highest level, someone might want to check equality of transactions, but we could special-case that by using transaction hashes.
