### ISSUE TITLE
Document types specified in 7.1 Transaction Encoding and Consensus as part of the consensus rules

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3222]
For each consensus rule:

- check that the rule is implemented in Zebra
- make sure the latest version of the rule is quoted in the docs for the code that implements it
- make sure the code implements the latest version of the rule

## Subtasks

- [x] #3420
- [x] #3421
- [x] #3422
- [x] #3423
- [x] #3424

## Zcash transaction format

https://zips.z.cash/protocol/protocol.pdf#txnencoding

### Up to transaction v4

![Screenshot 2021-12-16 at 16 27 07](https://user-images.githubusercontent.com/1311133/146401230-501ef3b7-7ff0-42e1-a586-ee8981baba76.png)

### Transaction v5

![Screenshot 2021-12-16 at 16 37 04](https://user-images.githubusercontent.com/1311133/146401491-c7464a6e-2350-4c15-b387-6aa5d3bf06e0.png)

## Implementation
 

See #3223

**Comment by mpguerra** [comment]
Not sure if we can do any easy documentation here or if it's all over the codebase...

**Comment by teor2345** [comment]
> Not sure if we can do any easy documentation here or if it's all over the codebase...

The format specs should be documented where the types are serialized and deserialized.

**Comment by teor2345** [comment]
Here is the split I'd suggest, because it matches the structure of Zebra's code (and also the spec):
- transaction header
- transparent
- sapling
- sprout
- orchard

You can see this split in the v5 transaction format, it's indicated using double lines. v1-v4 should follow the same split, even though the field order is different. The leftover JoinSplit fields are sprout fields.

We should cover all relevant transaction versions as part of each sub-ticket. (The code is repeated but usually identical.)

 @mpguerra can you assign people to the sub-tasks after you've split this task?

**Comment by oxarbitrage** [comment]
Closed by https://github.com/ZcashFoundation/zebra/pull/3491, https://github.com/ZcashFoundation/zebra/pull/3498, https://github.com/ZcashFoundation/zebra/pull/3499, https://github.com/ZcashFoundation/zebra/pull/3501 and https://github.com/ZcashFoundation/zebra/pull/3507
