### ISSUE TITLE
Send transactions in lightwalletd integration tests

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3512]
## Motivation

The `sendrawtransaction` RPC method in `lightwalletd` needs to be able to create and send transactions on the network.

We might need to do a full sync to make these tests work.
We might need a developer wallet to make these tests work on mainnet.

## Tasks

- Add a test harness that syncs to the tip from cached state
- Create a new transaction
- Add a lightwalletd integration test for `sendrawtransaction`

**Comment by teor2345** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3512?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @upbqdn

**Comment by jvff** [comment]
An idea on how to test this without having to set up an account and use real funds (which would limit CI execution and potentially make it more complicated due to the need to protect keys):

1. Spawn a zebrad instance
2. Pick a (recent?) block height
3. Get some transactions from blocks after that block height
4. Stop the zebrad instance
5. Spawn a new zebrad instance for lightwalletd to interface with
6. Synthetically limit this new zebrad instance to the chosen block height
7. Try to send the transactions that were obtained from future blocks

I guess the hardest part would be step 6. One idea might be to have an optionally compiled in service layer that intercepts state service calls and discards responses that would indicate data from heigher block heights.

Any opinions on this idea?

**Comment by teor2345** [comment]
> I guess the hardest part would be step 6. One idea might be to have an optionally compiled in service layer that intercepts state service calls and discards responses that would indicate data from heigher block heights.

Configure the `zebrad` instance with no seed peers, then it can't possibly get any new blocks.

(We already have a `debug_stop_at_height` config for step 4, and a `restart_stop_at_height` acceptance test for steps 1, 4 & 6.)
