### ISSUE TITLE
Store Sapling & Orchard note commitment trees in finalized and non-finalized state

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3563]
## Motivation

For #3156 we need to be able to return a Sapling & Orchard tree state (a note commitment tree, represented as a frontier, like we already do) for multiple block heights. ~~However, while we do store the Sprout trees for every height, for Sapling and Orchard we only store it for the finalized tip (and also for non-finalized tips, in memory).~~

ZecWallet Lite expects to have a tree state for every block from Sapling or Orchard activation, for good performance on first use.

~~We don't need to store them for _every_ height since `z_gettreestate` supports a `skipHash` return value that requests the caller to look up a tree in a previous height. But we do need to store them every X blocks for some value of X.~~

### Designs

- [ ] Change the sync to store all the Orchard & Sapling note commitment trees in the finalized and non-finalized state. This will require a database version bump.

## Follow Up Tasks

Optimisation:
- #3757

**Comment by teor2345** [comment]
I don't really have a strong opinion on this, but here are the design constraints:

Space:
- there are about 2 million blocks
- Zebra's state is about 25 GB
- each tree state takes up about 1 kB

Performance:
- there are about 1000 new tree states per day
- if a client is new, or it has been shut down for a while, it has to download up to `X` tree states before it can send transactions

And here is an example:

If we store 1 tree state every thousand blocks, we would use:
- an extra 1.5 MB for Sapling (0.01% of the database)
- a few kilobytes for Orchard

And new clients would have to download about the same amount of blocks as a client which had been offline for a day.

We should not store any extra tree states before a pool activates, because they are all identical.

**Comment by teor2345** [comment]
Any skip interval between 100 and 10,000 would probably be fine.
But choosing lower values improves wallet performance.

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3563?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
Aditya told us that ZecWallet requires every block's tree state for good performance. This will cost us about 1.5 GB for Sapling.

**Comment by upbqdn** [comment]
Should the note commitment trees be included in the non-finalized state as well?

**Comment by conradoplg** [comment]
> Should the note commitment trees be included in the non-finalized state as well?

I think so, since the non-finalized blocks can be queried too

**Comment by upbqdn** [comment]
Note: We store and query Sprout note commitment trees by anchors, not heights. I updated the description of the issue so that it reflects this.

Since #3156 will query the note commitment trees by heights, we will have to have two more column families in the database: `sapling_note_commitment_tree_by_height` and `orchard_note_commitment_tree_by_height`. Similarly, for the non-finalized state, the `Chain` structure will have two more members. I will use the same names for those.

I'm not going to include the Sprout note commitment trees because `lightwalletd` doesn't require them.

**Comment by teor2345** [comment]
> Since #3156 will query the note commitment trees by heights, we will have to have two more column families in the database: `sapling_note_commitment_tree_by_height` and `orchard_note_commitment_tree_by_height`. Similarly, for the non-finalized state, the `Chain` structure will have two more members. I will use the same names for those.

It looks like we already store sapling and orchard trees by height in the finalized state?
(But we delete every height except for the latest height.)

https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0005-state-updates.md#rocksdb-data-structures

https://github.com/ZcashFoundation/zebra/blob/699c0625f3e57edc732f834ed8b354cd8e11f423/zebra-state/src/service/finalized_state/zebra_db/shielded.rs#L260-L270

**Comment by teor2345** [comment]
I split out this optimisation task, because it's optional:
- #3757

But we might need it to get better performance.

**Comment by upbqdn** [comment]
I realized I forgot to mention this issue in the corresponding PR, so it didn't get closed. Should we close this?

**Comment by conradoplg** [comment]
> I realized I forgot to mention this issue in the corresponding PR, so it didn't get closed. Should we close this?

Sure! I linked the PR and I'm closing this
