### ISSUE TITLE
ci: do not allow merges to main with failed lightwalletd checks

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#3922]
## Motivation

CI has been stabilized up to a point we can start constraining the PR that can be allowed into `main` with specific valid checks. And as the `lightwalletd` development has been prioritized, this is one of the tests we'd like to 

### Specifications
We'd like to enforce tests related to `lightwalletd`

### Designs

- Enforce GitHub checks for lightwalletd jobs
- Enforce Mergify checks for lightwalletd jobs 

## Related Work

None so far

**Comment by teor2345** [comment]
> * Enforce Mergify checks for lightwalletd jobs

Mergify uses a config file in git, so is harder to disable if there's a temporary problem. But it's also harder to disable accidentally.

Since lightwalletd is our top priority right now, I think it's ok to strongly and redundantly enforce these checks.

(But my preference for unstable checks is to only use GitHub settings, so any one of 3 admins can disable them.)
