### ISSUE TITLE
`zebra seed` command is throwing a panic but keeps going fine?

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#394]
![image](https://user-images.githubusercontent.com/552961/82921787-ca5f6d00-9f46-11ea-95ae-4361f5dbc3f5.png)

```
May 26 11:47:58.437  INFO zebrad::components::tracing: Initializing tracing endpoint
May 26 11:47:58.438  INFO zebrad::components::metrics: Initializing metrics endpoint
May 26 11:47:58.438  INFO zebrad::commands::seed: begin tower-based peer handling test stub
May 26 11:47:58.448  INFO add_initial_peers: zebra_network::peer_set::initialize: Connecting to initial peer set initial_peers=[V4(3.136.31.59:8233), V4(34.66.191.95:8233), V4(138.197.158.219:8233), V4(3.19.66.87:8233), V4(47.254.18.12:8233), V4(198.187.30.208:8233), V4(47.254.69.198:8233), V4(192.64.112.23:8233), V4(81.2.80.52:8233), V4(51.89.96.119:8233), V4(213.227.145.69:8233), V4(62.210.91.14:8233), V4(52.30.69.116:8233), V4(139.59.187.105:8233), V4(46.4.192.189:8233), V4(47.254.178.251:8233), V4(116.203.188.195:8233), V4(47.254.179.213:8233), V4(95.216.227.171:8233), V4(94.156.174.100:8233), V4(5.9.193.19:8233), V4(89.234.183.220:8233), V4(118.24.175.14:8233), V4(47.94.251.211:8233), V4(162.14.4.106:8233), V4(3.92.199.184:8233), V4(47.252.1.134:8233), V4(47.254.18.12:8233), V4(198.187.30.208:8233), V4(164.132.122.137:8233), V4(52.30.69.116:8233), V4(51.77.64.61:8233), V4(78.129.149.90:8233), V4(51.77.64.51:8233), V4(116.202.100.25:8233), V4(95.216.227.171:8233), V4(46.4.192.189:8233), V4(47.254.179.213:8233), V4(167.86.124.82:8233), V4(188.72.203.154:8233), V4(116.202.105.79:8233), V4(173.249.53.153:8233), V4(139.59.128.41:8233), V4(95.216.46.146:8233), V4(85.15.179.171:8233), V4(3.112.252.179:8233), V4(13.231.145.68:8233), V4(47.244.58.44:8233), V4(47.106.224.223:8233), V4(119.23.67.66:8233)]
May 26 11:48:01.314  INFO zebra_network::peer_set::initialize: Sending initial request for peers
May 26 11:48:01.314  INFO zebrad::commands::seed: waiting for peer_set ready
May 26 11:48:01.314  INFO zebrad::commands::seed: peer_set became ready
The application panicked (crashed).
Message:  assertion failed: !self.cancel_handles.contains_key(&key)
Location: <::std::macros::panic macros>:2

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
May 26 11:48:01.354 ERROR zebra_network::peer_set::initialize: e=send failed because receiver is gone
```

**Comment by yaahc** [comment]
```rust
                Poll::Ready(Some(Err((key, UnreadyError::Canceled)))) => {
                    debug_assert!(!self.cancel_handles.contains_key(&key))
                }
```

So this is likely a background panic that is taking down the thread this service is running in and then not being properly propogated back to main, digging into how tower and services work to get an idea of where the panic is being discarded.

**Comment by yaahc** [comment]
Okay so the issue is in `tower::buffer::Buffer` https://docs.rs/tower-buffer/0.3.0/src/tower_buffer/service.rs.html#46

It spawns the buffered future but discards the join handle immediately. I'm gonna open an issue and PR against tower and test out the PR against `zebra seed` via a patch in the toml.

**Comment by yaahc** [comment]
Okay so that was only part of the issue, and not the main part. The main issue is that `zebra_network::init` spawns multiple futures in background threads and discards the join handles. Ideally we'd want to return the join handles so they can be awaited after the service is done running.

I'm worried that this will still leave room for futures to be dead in background threads for a long time before errors get awaited and propagated.

As I see things there are three approaches we could take to improve this

### A. Return 3rd future from init to shut down the various spawned tasks and await their results.

The specific approach I'm thinking of is:

- Create a new zebra_network::Handle type or something
- add a shutdown method to it that returns a future which sends the signal to the background tasks to wrap up (assuming they're even long running) and then waits on all their stored join handles, propagating any errors it encounters back out.

### B. Avoid using `tokio::spawn`

I think we could restructure things to run all parallel futures via combinators like `try_join!` or w/e they're called, this would let us exit immediately if one of the futures encounters an error, I'm not sure what implications this would have for `zebra_network`'s api though, so maybe its not a great idea. However I do feel like getting panics to fail fast is a good goal.

### C. use `panic=abort`

This is basically the exact thing that I want, it disables unwinding and makes it so a panic in any thread kills the whole process immediately. This also disables all the unwinding code generation so it has perf advantages. This is by far my favorite option. If it helps at all, `firefox` uses `panic=abort`.

**Comment by yaahc** [comment]
RE: using `panic=abort`

To quote @mystor

> all libs need to be written to support panic=unwind
> And certain libs don't behave correctly with panic=abort

So we might want to add testing for `panic=unwind` in CI or something to ensure that everything is still well behaved if panics are handled rather than instantly bringing down the whole process.

**Comment by yaahc** [comment]
My inclination is to do a mix of A) and C), Doing C handles panics and gives us the fast fail behaviour. A gives us proper error propagation which ensures that everything gets reported properly and covers situations where we don't care about failing asap.

**Comment by dconnolly** [comment]
> My inclination is to do a mix of A) and C), Doing C handles panics and gives us the fast fail behaviour. A gives us proper error propagation which ensures that everything gets reported properly and covers situations where we don't care about failing asap.

We did C) in #401, we are looking to do A) as part of a separate piece of work/issue.

**Comment by dconnolly** [comment]
A): #408
