### ISSUE TITLE
ci: only run the full sync test on mergify PR and after main branch merges

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4136]
## Motivation

In PR #4107, we started running the full sync test on all PRs.

But we only want to run it:
- on Mergify PRs
- after merging to the `main` branch
- on manual workflow dispatch requests

**Comment by gustavovalverde** [comment]
> But we only want to run it:
> 
> * on Mergify PRs
> * after merging to the `main` branch

I'm not sure if there's value added from running it on Mergify PRs right now, as it's (almost) the same as running it in main because we're not enforcing the full sync before merging. And based on the amount of time it takes for the full sync to complete, it might make things slower before merging.

But I do agree we should remove it from the PR for the time being, and add a TODO to the pipeline.

**Comment by teor2345** [comment]
> I'm not sure if there's value added from running it on Mergify PRs right now, as it's (almost) the same as running it in main because we're not enforcing the full sync before merging. 

Do we need to run a full sync on Mergify PRs to get the lightwalletd integration tests to work?
If the state version changes, we need to regenerate a cached Zebra state to run lightwalletd full sync tests.

> And based on the amount of time it takes for the full sync to complete, it might make things slower before merging.

But merging doesn't wait for the full sync job?

**Comment by teor2345** [comment]
Obsoleted by #4153
