### ISSUE TITLE
Create `NextPeerService`

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#45]
A service or component that will manage metadata about the available peers and their health/availability/latency, and a method or main service call that will return the best/next peer to connect to.

**Comment by hdevalence** [comment]
A very basic initial stub for this could just be a wrapper around a `Vec<SocketAddr>` that yields one address at a time.

**Comment by hdevalence** [comment]
Should the output of this service be a `PeerClient` (i.e., it handles connections) or just a `SocketAddr` (i.e., it is just responsible for determining which peer to connect to, and its parent then uses a `PeerConnector`)?

**Comment by hdevalence** [comment]
To prevent duplicate connections, we need to distinguish live peers we are currently connected to from peers we recently talked to but are not currently connected to.  This means that we need to ensure that we send outgoing ping messages, so that we know that if we have not heard a message from a peer in X time, we are not connected to it (where X is chosen to be longer than the ping interval), so this depends on #49.

**Comment by hdevalence** [comment]
Closed by #78
