### ISSUE TITLE
zebrad panics when an inbound network request fails 

### ISSUE THREAD

**Issue by madars** [ZcashFoundation/zebra#4781]
# Analysis and Suggested Fix

See https://github.com/ZcashFoundation/zebra/issues/4781#issuecomment-1185037404

# Bug Report

After a few days of running, including being at the tip of the blockchain a lot of the time, my zebrad instance crashed and generated this auto-report:

## Error
```
channel is closed: TryRecvError
```

## Metadata
|key|value|
|--|--|
|**version**|1.0.0-beta.12+15.gf7889ac|
|**Zcash network**|Mainnet|
|**state version**|25|
|**branch**|main|
|**git commit**|f7889ac|
|**commit timestamp**|2022-07-12T00:16:19Z|
|**target triple**|x86_64-unknown-linux-gnu|
|**build profile**|debug|
|**location**|zebra-network/src/peer/client.rs:215:14|

## SpanTrace

<details>

```
SpanTrace:
   0: zebra_network::peer::connection::msg_as_req
           with [3mmsg[0m[2m=[0m"inv"
             at zebra-network/src/peer/connection.rs:979
   1: zebra_network::peer::handshake::
           with [3mpeer[0m[2m=[0mOut("135.181.18.180:8233")
             at zebra-network/src/peer/handshake.rs:791
   2: zebrad::application::
           with [3mzebrad[0m[2m=[0m"f7889ac" [3mnet[0m[2m=[0m"Main"
             at zebrad/src/application.rs:383
```
</details>

I will relaunch it with `RUST_BACKTRACE=full` now

**Comment by teor2345** [comment]
@madars thanks for this bug report, can you send us a copy of the `zebrad` logs that happened before the crash?

It's ok if you don't have them. I think we can fix this bug, but it would be nice to know why it happened.

**Comment by teor2345** [comment]
Analysis:

When an error happened on an inbound peer request, `zebrad` panicked in `close_and_flush_next()`:
https://github.com/ZcashFoundation/zebra/blob/0e06c11ff098874415a5f3a1ab3a3bea2d580e1e/zebra-network/src/peer/client.rs#L208-L216

This panic happens because [`futures::channel::mpsc::Receiver::try_next()`](https://docs.rs/futures/latest/futures/channel/mpsc/struct.Receiver.html#method.try_next) returns an error after the channel is closed. But the documentation says that errors only happen:
> `Err(e)` when there are no messages available, _*but channel is not yet closed*_

It seems like the documentation is incorrect, and errors can be returned after `close()`. When that happens, we should return `None` instead of panicking.

Returning `None` will make `Connection::shutdown()` finish clearing requests on the failed connection. Then the connection will finish its cleanup, and disconnect from the peer.

This bug might have been revealed by the panic fix in PR #4770.

**Comment by madars** [comment]
@teor2345 I unfortunately don't have the console output so unless there is a log file somewhere, I don't have them. (The `.log` files in `state/v25/mainnet/` are for the DB right?) For future reference, what is the recommended practice to run zebrad with logging? Should I just pipe its output in `tee` or similar?

**Comment by teor2345** [comment]
> @teor2345 I unfortunately don't have the console output so unless there is a log file somewhere, I don't have them. (The `.log` files in `state/v25/mainnet/` are for the DB right?)

Yes, that's a RocksDB log file.

> For future reference, what is the recommended practice to run zebrad with logging? Should I just pipe its output in `tee` or similar?

@madars that's what I do.

You might also want to use the [tracing.force_color](https://doc.zebra.zfnd.org/zebrad/config/struct.TracingSection.html#structfield.force_use_color) option to get color output to your terminal.

Or there's the `use_journald` option, if you'd prefer to use `systemd` logging.
