### ISSUE TITLE
Quick fix for sync test timeouts in CI

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4910]
## Motivation

Some of Zebra's sync tests are currently failing in CI on the main branch and other PRs.

### Possible Solutions

- increase the test timeouts
- update the Zebra checkpoints

We have other open tickets that will fix these performance issues, but we need a quick fix so we can continue working on them.

These failures block almost every `zebrad` and Zebra DevOps task in this sprint.

**Comment by oxarbitrage** [comment]
There is an additional problem in the CI related to clippy and the last version of it https://github.com/ZcashFoundation/zebra/pull/4918/checks?check_run_id=7885954690

It seems the problem is in the `prost` crate. Here someone tries to fix it but didn't worked out: https://github.com/tokio-rs/prost/pull/704
I think they ended up removing clippy at https://github.com/tokio-rs/prost/pull/702 however is hard to tell as they dont explain anything on their pull requests. 

If they fix it and tag a release soon we should upgrade `prost` and probably `tonic` and `tonic-build` in the same pull request.

**Comment by teor2345** [comment]
> There is an additional problem in the CI related to clippy and the last version of it https://github.com/ZcashFoundation/zebra/pull/4918/checks?check_run_id=7885954690
> 
> It seems the problem is in the `prost` crate. Here someone tries to fix it but didn't worked out: [tokio-rs/prost#704](https://github.com/tokio-rs/prost/pull/704) I think they ended up removing clippy at [tokio-rs/prost#702](https://github.com/tokio-rs/prost/pull/702) however is hard to tell as they dont explain anything on their pull requests.

They gave up on making clippy pass in their CI, which pushes the work onto downstream users.

But we still want clippy to pass in our CI, so I'll open a PR to fix it tomorrow.
(This is a different bug to CI timeouts, so it should get a different PR.)
