### ISSUE TITLE
ci: If a cached disk image is manually triggered it won't be used by the opened PR

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#4964]
## Motivation

When triggering a full sync or checkpoint sync from a branch, we might expect that a successful build of the cached disk image would be available for following workflow runs in the same branch (this will mostly be a PR in practice). But this won't happen as the GitHub reference for manual trigger uses the `branch name` and the automatic workflow runs on a PR uses the `PR reference` which is `merge-<pr_id>`

### Designs

When searching for disks in a PR, also search for disks having the branch name, and not just the PR reference

## Related Work

This was found while working with https://github.com/ZcashFoundation/zebra/issues/4295

**Comment by teor2345** [comment]
We don't want to prioritise previous commits from the same PR, because we want to be testing with the output of the current commit.

We've had bugs where the cached state created by previous commits worked, but the current commit was failing. While we can't avoid them entirely due to performance reasons, I don't want to make them more likely.

**Comment by gustavovalverde** [comment]
Just to be clear on this one, if you manually trigger a full sync and/or checkpoint sync from a branch/PR, the disk image will just be created but never used afterwards.

We either allow the branch to use this image, which might have the actual commit if a re-run is triggered, or never create it as it won't be used anyways.
