### ISSUE TITLE
Make in_memory modify the state in the async block

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#510]
ZebraState's in_memory implementation modifies the state in the service's call(). But on_disk modifies the state in the async block, once the future runs.

This implementation difference might cause confusing "premature add" bugs, if a state user creates a future, and then drops it.

We should make the behaviour consistent, and add tests for it.

(There's no need to change read-only state queries.)

**Comment by hdevalence** [comment]
Is this something that we should make consistent? It feels to me like an implementation detail that we shouldn't be exposing in our API  — in particular, I don't think any code should make a service call and then expect that dropping the future "undoes" the request.

**Comment by yaahc** [comment]
I think I lean in favor of making it consistent, just to remove potential footguns.

**Comment by hdevalence** [comment]
I don't think that making it consistent removes a potential footgun, it ensures that the footgun remains in place, because (in my view) the footgun is trying to "undo" a request by dropping the future.

I'm also not even sure this is possible -- consider a service that's behind a buffer, and `call` on the outer service passes the request off to a worker task.  Relying on processing to not start until after the response future is `await`ed I think involves racing the worker task against the caller task.

It's fine to treat dropping the future as a cancellation, that a service can optionally use to abort early or skip processing, but it's not reasonable to expect that a service should roll back any intermediate state changes when that happens, or have to structure itself internally so that this is possible: the whole reason that `Service::call` takes `&mut self` is to allow stateful processing. By analogy, if we made a `POST` request to some remote web service, and didn't wait for the response to come back, we would not expect the web service to not have processed our request.

**Comment by yaahc** [comment]
Okay, I get that logic, the issue is that you cant rely on work not being irreversibly done before you ever await a future, so the behaviour that we see in `in_memory` isn't different behaviour, it is actually a subset of the behaviours we can observe with `on_disk`. So changing between the state layers isn't changing the behaviour, its just forcing it into the subset of behaviour that could expose the bug "depending on drop preventing work from happening" that might have been missed before because you were consistently winning a race. So if anything this makes the behavioural difference an advantage which we should prefer to maintain. I'm on board with this logic.

**Comment by teor2345** [comment]
So there aren't any guarantees that requests are transactional. That makes sense.

But if we're going to do unit tests with state in_memory, then run the app with state on_disk, how do we detect app bugs that are caused by the differences in those implementations?

We could:
1. Run all our unit tests against on_disk
2. Run all our unit tests against both state implementations

To get good coverage, we'll need to write unit tests that fail each specific verification (or state) check.

If we don't have those tests, we could commit bugs like:
https://github.com/ZcashFoundation/zebra/pull/492/files#diff-7ea86ca07b5d02f05830fd0d71b593f1R68-R86

In any case, I think we should:
* Document that the implementation might change state during `call()`, or in the Future's async block.

Can a particular service make some state changes in `call()` and others in the async block? Or should we guarantee that each service chooses one of those places to make state changes?

Splitting state changes could lead to partial state updates, with:
* unpredictable delays between related state changes, or
* partial state updates never completing, if the future is never run.

I don't think that's what we want.

**Comment by hdevalence** [comment]
To clarify, I think that requests *should* be processed transactionally -- either the request is processed, or it isn't -- but I don't think that we can make any guarantees about when those transactions are processed before the response future resolves.

For the validation strategy, I think that we should aim to test:

1. that the on_disk backend matches the in_memory backend on an arbitrary sequence of requests;
2. that various state-using subsystems behave correctly with the in_memory backend.

**Comment by yaahc** [comment]
> that various state-using subsystems behave correctly with the in_memory backend.

I think focusing on testing via the `in_memory` backend might be a mistake, given that it will only exhibit a subset of the behaviour we will encounter with `on_disk`'s backend. I think the most important thing is that we test our code against a backend that will exhibit both behaviors of sometimes processing the transaction before the future is awaited and sometimes processing the transaction in response to the future being awaited. Right now the only backend with this property is `on_disk`. If we moved the processing for `in_memory` into the future I think it would start to exhibit both behaviors, thanks to the `Buffer` that wraps it, which would make it an acceptable backend for test purposes.

Along those lines, we might want to do some testing on the various backends to see how often the futures are resolved before awaiting and how often the await has to suspend its caller, though I'm not sure how to do this. Once we have this infomation however we should be able to evaluate if one of the possible behaviours is being mostly avoided, and if so we can modify the `in_memory` backend to artificially bias it towards the otherwise under tested code path which would then make it the ideal backend for testing purposes.

**Comment by hdevalence** [comment]
The alternative, which we're already doing, is to just not write code that depends on calling `poll` an exact number of times, instead of polling the future until it's ready and then seeing if there's an error.  Since the only time this came up was in code that called `Service::call` before deciding whether it should actually make the service call and dropping the response otherwise, I'm not sure that this will actually be a problem for us.  If it ever re-occurs, we could try to find a better solution, but for now, I'm not sure that this is a priority.
