### ISSUE TITLE
Tests panic with "failed to set global default subscriber" due to install_tracing() race

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#515]
Sometimes, when I call `install_tracing()` in an async test, I get a panic with "failed to set global default subscriber" at tracing-subscriber-0.2.5/src/util.rs:75:9.

I think this is a race condition, because calling `install_tracing()` from multiple async functions makes it happen more often. And deleting all but one `install_tracing()` call seems to avoid the panic.

I think we should only call `install_tracing()` once per launch, but I don't know how to do that.

**Comment by yaahc** [comment]
If you're copy pasting the `install_tracing()` that I setup it should be using a `std::sync::Once` to ensure that the global initialization only happens once. 

https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/lib.rs#L96-L99

If this is somehow getting called multiple times that is extremely worrying...

**Comment by teor2345** [comment]
zebra-consensuses has an old version, without the Once:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/verify.rs#L113

I can't copy the Once variable itself, because each separate Once instance can execute independently.

Where can we put this shared utility code?
Each crate needs its own copy when built separately, but they need a shared copy in the app.

**Comment by yaahc** [comment]
I think its fine to copy the once so long as its one per crate, each crates unit tests should have their own process so they won't collide.

As for where to put the shared utility code, I was thinking we should take `zebra-test-vectors` and rename it to `zebra-test` and make that the crate where we store all of our shared test utilities and artifacts. Take the existing vectors and shove them in a `mod vectors;` and then put `install_tracing()` in the root. We will probably want to rename it to just `install` or `init` because I'm also gonna shove some `eyre` stuff in there.

**Comment by teor2345** [comment]
Fixed in #538 in 7bdf6f6fe8de1ea092c4cfea4ae44c7da2001aa4 for verify/block (but not checkpoint).

I also added a TODO for @yaahc to move `install_tracing()` to zebra-test. I'm leaving this ticket open until we fix the issue across Zebra.

**Comment by teor2345** [comment]
Fixed in #538 in 8e30964baa109493213b8490d5e40aa9083a2090 for checkpoint.

**Comment by dconnolly** [comment]
This has been resolved
