### ISSUE TITLE
Different dependency versions across the zebra crates

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#539]
Some of our Cargo.toml files have slightly different dependency versions. For example, tracing 0.1 vs 0.1.15 in:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-network/Cargo.toml#L30
https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/Cargo.toml#L21

I'm not sure what the exact impact is here, but the build seems to work. I wonder if we are compiling redundant dependencies, or slightly different dependencies.

I don't think we need to fix this issue for the alpha release. But it would be nice to fix it for stable.

**Comment by hdevalence** [comment]
I don’t think there’s anything to fix here, Cargo is already doing the right thing and unifying dependencies to the extent that is possible.

All of the version requirements in Cargo are implicitly range requirements unless otherwise specified, so “0.1” means “0.1.x” and “0.1.15” means “0.1.y where y >= 15”.  Cargo does dependency resolution on a workspace-wide basis and always selects exactly one version in each semver range.

**Comment by yaahc** [comment]
also fwiw if you wanna check for duplicate dependencies you can run `cargo tree -d`. We have a few and I'd like to fix that up to minimize our build times but I don't think its urgent.

**Comment by teor2345** [comment]
Duplicates could also result in subtle bugs, if internal details in different versions are incompatible.

**Comment by hdevalence** [comment]
One property that helps minimize that possibility is that Cargo requires a *unique* version in each semver compatibility range of each named dependency (so if two dependencies are possible to unify, they will be unified) and treats incompatible versions of the same named dependency as different crates (so all of their types are distinct and they are not interchangeable).

**Comment by yaahc** [comment]
yea in my experience I've only ever had duplicate versions cause issues that showed up as compiler errors due to types mismatching. I've never encountered runtime errors due to mismatched versions. I don't think there are many version mismatches that we could run into that could have these kinds of issues. sled is the only dep that I know of that could because the diff versions could hit the same file, but we're probably never gonna accidentally duplicate sled as a dep, only the state crate should ever track it.

**Comment by teor2345** [comment]
Sounds great, I'm going to close this ticket then.

If it is important to run `cargo -d` before the alpha release, let's open a separate ticket.
