### ISSUE TITLE
Fix frequent "synced block height too far ahead of the tip: dropped downloaded block" errors

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#5420]
## Motivation

There are a high number of these logs in [zebra v1.0.0-rc.0's full sync logs](https://github.com/ZcashFoundation/zebra/actions/runs/3259396265/jobs/5374412073#step:6:19731), and there's a comment where the logs are being emitted saying that this error should be very rare during normal operation. (https://github.com/ZcashFoundation/zebra/blob/main/zebrad/src/components/sync/downloads.rs#L397-L401)

<details>

```
INFO {net="Main"}:sync:try_to_sync:extend_tips: zebrad::components::sync::downloads: synced block height too far ahead of the tip: dropped downloaded block hash=block::Hash("0000000000ce576515d2503d08cc20da70f6d20fd0ac703bef89083321d7173e") block_height=Height(1742608) tip_height=Some(Height(1739006)) max_lookahead_height=Height(1742206) lookahead_limit=800
```

</details>

### Possible Solution

- Increase `max_lookahead_height`

**Comment by teor2345** [comment]
I agree this is a waste of download capacity and sync time.

> * Increase `max_lookahead_height`

Increasing the lookahead height will increase Zebra's memory usage, which I'd prefer not to do. And it might not solve the issue, because the syncer will download more blocks in response to the increased lookahead height.

Instead, we could increase the lookahead multiplier in the sync downloader? This allows more lookahead capacity, without downloading any extra blocks.

It's also possible that fixing the sync hangs on the first non-finalised blocks (#5125) will help fix this issue. But we should only do that if this issue is happening near the first non-finalised blocks, and not any other blocks.

**Comment by teor2345** [comment]
Parallelising note commitment tree updates (#5425) might also fix this issue, or it might have no impact, it's hard to know until we do it.

**Comment by mpguerra** [comment]
Do we know why this has started happening now?
