### ISSUE TITLE
Broken link in Zebra documentation Config section

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#5436]
## Description

In the `zebrad` config section of the [documentation](https://doc.zebra.zfnd.org/zebrad/config/struct.ZebradConfig.html) the `ConsensusSection` link gives a `404 not found` error.

### Steps to Reproduce

Go to https://doc.zebra.zfnd.org/zebrad/config/struct.ZebradConfig.html and click on `ConsensusSection` 

![screenshot_from_2022-10-20_06-10-47](https://user-images.githubusercontent.com/1311133/196960488-1037bee9-e7ea-4602-8b2f-df7c77113f7d.png)

The link points to  https://doc.zebra.zfnd.org/zebra_consensus/zebra_consensus/config/struct.Config.html but maybe it should point to: https://doc.zebra.zfnd.org/zebra_consensus/config/struct.Config.html instead?

**Comment by oxarbitrage** [comment]
In a quick look this is weird. In the internal docs the link is not broken https://doc-internal.zebra.zfnd.org/zebrad/config/struct.ZebradConfig.html

and i was not able to find anything in the code that can be causing it. I saw that zebra-consensus dependency is called with a trailing `/` in zebrad: https://github.com/ZcashFoundation/zebra/blob/main/zebrad/Cargo.toml#L72 while all the others do not trail. 

I don't think this is the cause here but we can try.

**Comment by teor2345** [comment]
This seems like a rustdoc bug, rather than a Zebra bug.

We might be able to work around the bug by naming the types directly, rather than renaming them on import.

For example:
* ConsensusSection -> zebra_consensus::Config

**Comment by oxarbitrage** [comment]
Unfortunately, the refactor we made in https://github.com/ZcashFoundation/zebra/pull/5460 do NOT fix the link issue: https://doc.zebra.zfnd.org/zebrad/config/struct.ZebradConfig.html

**Comment by mpguerra** [comment]
This doesn't seem to be happening anymore...
