### ISSUE TITLE
discuss trait impl organization strategy in `zebra`

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#556]
Right now there seems to be some inconsistency with how we organize trait impls. https://github.com/ZcashFoundation/zebra/issues/220#issuecomment-582644124 requested that we move all arbitrary impls to a single file, but once I implemented this change in https://github.com/ZcashFoundation/zebra/pull/553 concerns were raised over having trait impls being in a diff file from the struct definitions.

I think it might be a good idea to come to a consensus on how this should be handled, not just for `Arbitrary` but in general. We already seem to be moving `ZcashSerialize`/`ZcashDeserialize` impls away from their struct definition files in some cases. I don't really mind if we have some traits that are special cased where we like to consolidate all impls of that trait to a single file but I do think we should come up with a consistent rule to apply to all traits and all instances of any given trait.

**Comment by hdevalence** [comment]
I have a pretty strong preference for consolidating the `Arbitrary` impls in one place with the other code. 

The primary reason is that I think that conditionally-compiled functionality should be grouped together in submodules to the greatest extent possible, so that conditional compilation affects entire module subtrees, rather than individual items. There are a few reasons why I think this is good as a general principle:

1. Because module subtrees can be broken out into files and directories, it's much easier to determine under what conditions some item is or isn't included in the build, because those conditions are generally done once (at the root of the subtree) rather than attached to each item.

2. In case the conditions for conditional compilation ever need to change, it's much easier to change them in one place rather than many places.  (One way I like to think about this structuring choice is as "factoring out" the conditions to a single branch-point in the module tree).

3. Code conditionally compiled under the same conditions is usually thematically related, so keeping that thematically related code together usually fits well anyways.

A separate question is about whether trait impls should be consolidated in one place, as we do with the serialization code.  I also think that this is a good practice, because it allows all of the thematically related code to be colocated.  For instance, in the case of `ZcashSerialize` and `ZcashDeserialize`, the serialization routines for each structure are far more thematically similar to each other than each of them is to the definition of the structure they correspond to.  Keeping these impls together means that there's a single place to see all of the serialization code.  Similarly, the `Arbitrary` impls are extremely similar to each other, but completely dissimilar to the rest of the code defining the structures they generate.

This raises the question: if some trait impls make sense to group together, as in those cases, does it always make sense? No. So what is the criteria for when it makes sense to group them with the structure definitions and when it makes sense to group them with each other.  My opinion is that this should be based on a judgement of whether the behavior provided by the trait is conceptually intrinsic to the definition of the struct or not.

For instance, in the case of `ZcashSerialize` and `ZcashDeserialize`, the serialization behaviour is not conceptually intrinsic to the definitions of the structures, since we quite deliberately wrote those structures to be different from the way that Bitcoin encodes them. In the case of `Arbitrary`, the key insight of the `proptest` crate over the `quickcheck` crate is that a `Strategy` for producing instances of a type is not a property of the type, but a conceptually separate thing -- there can be multiple generation strategies for a single type.  This also points me away from thinking that they should be grouped with the structure definitions.

One [concern](https://github.com/ZcashFoundation/zebra/issues/220#issuecomment-650405891) raised by @dconnolly is that separating the structure definitions and the generation strategies could lead to drift between the two.  I don't agree that this is a significant risk, because I think that almost any drift (e.g., adding a new field to a structure, etc) would cause a compile error (missing fields, type errors, etc).  If we didn't have a strong type system, things might be different, but my opinion is that the consistency benefits of the type system far outweighs the consistency benefits of code colocation.

**Comment by yaahc** [comment]
This sounds like a decent justification to me and I don't feel nearly as strongly about the placement as I do about the consistency, so I'm fine with opting to consolidate Arbitrary and ZCash.*erialize trait impls pending feedback from @dconnolly and @teor2345 

As for the `cfg` consolidation. I agree that having the same cfg peppered all over the place is annoying, two issues though:

1. I don't think the condition changing concerns are applicable to `Arbitrary` impls. In general I do agree with this logic for minimizing the number of `cfg` attrs we use but for `Arbitrary` impls I can't see the attribute ever needing to be changed from `test`.
2. Should we apply this logic to all `#[cfg(test)]` attrs in the codebase? I've noticed we pretty often have 5 or more `#[cfg(test)]` attrs in each file on various impls and use statements, and in some cases we even use `#[cfg(test)]` in `tests` modules that are themselves conditionally compiled.

**Comment by hdevalence** [comment]
1. Yeah, that list is meant as a general statement about conditional compilation, I agree that the condition-changing is unlikely for this case.

2. Yes, I think we should at most have one `#[cfg(test)]` item per module, unless there's some obstactle that makes it impossible.  For instance, I don't think we can get around having to conditionally add a `#[derive(Arbitrary)]`, but to the greatest extent possible I think we should aim to have as few conditional attributes as possible.

**Comment by teor2345** [comment]
I agree with consolidating similar code.

I think that my `Arbitrary` example was an edge case: a new parsing constraint, on an existing type, that affects the `Arbitrary` generation. If I had forgotten to change the `Arbitrary` impl, then we might have eventually failed a test. (If `Arbitrary` generates 2 MB structs.)

In most cases, the type system will fail compilation. And most other changes would be caught by the tests. (Still, it's a good idea to check that we have an Ok and Error test for each constraint.)

**Comment by dconnolly** [comment]
> ...  I think that almost any drift (e.g., adding a new field to a structure, etc) would cause a compile error (missing fields, type errors, etc). If we didn't have a strong type system, things might be different, but my opinion is that the consistency benefits of the type system far outweighs the consistency benefits of code colocation.

This is true, if `impl Arbitrary` is not gated by `[cfg(test)]`, but they usually are, so by default, compilation and checks are run under the --dev profile, and the test-gated stuff is not checked. We will only find the drift when we run the tests or compile using the test profile. This has bit me several times.

When I think about it, having a `tests.rs` or similar submodule in the directory structure under the main module, like we have for `serialize.rs` (àla `block` or `transaction` or `keys/sapling/`) is not so bad, especially as a module starts to grow. I just want to keep it as close to its own code as possible, and shunting 'all the test-specific code into a test-specific corner' is where test code goes to die IME. 

Putting a module's `Arbitrary`s or `Strategy`-producing code in its own `[cfg(test)]`able module, but alongside other trait impls, seems ok.

**Comment by yaahc** [comment]
> We will only find the drift when we run the tests or compile using the test profile. This has bit me several times.

@dconnolly this might be a diff between rust-analyzer on emacs and on vscode, I know this was an issue for me when I was using vim, but with vscode rust-analyzer always runs full compilation of all targets when it checks for errors in the background which would help you catch these `#[test]` only compilation errors early. You might want to look into what args vscode is passing to r-a and copy those over into your emacs setup.

**Comment by yaahc** [comment]
> Putting a module's Arbitrarys or Strategy-producing code in its own [cfg(test)]able module, but alongside other trait impls, seems ok.

I'm going to take this as consensus, here's the rule of thumb as I'm interpreting it:

1. put `ZcashSerialize`/`ZcashDeserialize` impls into a `serialization` file when there are many of them within a single module.
2. minimize `#[cfg]` attrs as much as possible, for `#[cfg(test)]` prefer to only have one attr on a submodule that contains all test code that is conditionally compiled, `derive(proptest_derive::Arbitrary)` however is an exception because it can't be moved.
3. For all other trait impls put them with the type they're implemented for, preferably after all non trait impl blocks for that type, but before any other type definitions.

**Comment by dconnolly** [comment]
> 1. put `ZcashSerialize`/`ZcashDeserialize` impls into a `serialization` file when there are many of them within a single crate.

@hdevalence do you really want to put all the zcash_serialize/deserialize impl's in one file in -chain etc? Keeping them where they are (close to the code that if it changes, so will the impls, in their own `serialize.rs`) seems fine. I don't see a win of putting all of them in a pile.

I'm balancing 'ease of maintainability' and 'where _should_ things go based on their characteristics', and since humans are the once reading and writing code, I lean towards the former.

**Comment by hdevalence** [comment]
To clarify, what I meant was the existing structure of `zebra_chain`, where, e.g., all of the transaction-related structures have a common module for serialization impl.s

**Comment by dconnolly** [comment]
> To clarify, what I meant was the existing structure of `zebra_chain`, where, e.g., all of the transaction-related structures have a common module for serialization impl.s

OK, that makes more sense to me. 👍

**Comment by dconnolly** [comment]
So this is not on a crate-basis, but module-basis:
> put ZcashSerialize/ZcashDeserialize impls into a serialization file when there are many of them within a single crate.

**Comment by yaahc** [comment]
edited the comment above to mention modules instead of crates

**Comment by teor2345** [comment]
> When I think about it, having a `tests.rs` or similar submodule in the directory structure under the main module, like we have for `serialize.rs` (àla `block` or `transaction` or `keys/sapling/`) is not so bad, especially as a module starts to grow. I just want to keep it as close to its own code as possible, and shunting 'all the test-specific code into a test-specific corner' is where test code goes to die IME.

I'm also concerned about test code dying in a corner. But if tests are at the end of a big file, I'm not sure that's much better.

Let's try to build testing into our PR guidelines, code reviews, and other processes? It would be great to have an automated, reliable bot that says "oops, no tests".

**Comment by yaahc** [comment]
I think its safe to say this is resolved and that https://github.com/ZcashFoundation/zebra/issues/556#issuecomment-651991537 was the final verdict
