### ISSUE TITLE
getblocktemplate RPC: Check if Zebra is still syncing lots of blocks, and return an error if it is

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#5675]
## Motivation

In order to be sure that Zebra is synced to the tip for the `getblocktemplate` RPC call we need to:

- check if Zebra has finished syncing blocks
- allow the same clock skew as the Zcash network, which is 100 blocks, based on the standard rule:

### Specifications

> a full validator MUST NOT accept blocks with nTime more than two hours in the future according to its clock. This is not strictly a consensus rule because it is nondeterministic, and clock time varies between nodes.

https://zips.z.cash/protocol/protocol.pdf#blockheader

## Related Work

#5466

**Comment by arya2** [comment]
I'm thinking I'll move the sync status module into zebra-network for this issue.

**Comment by teor2345** [comment]
> I'm thinking I'll move the sync status module into zebra-network for this issue.

This could be a really big functional change, which would impact sync reliability.

`SyncStatus` currently uses the most recent sync lengths from the syncer, which is in `zebrad`. This is not the same as the number of recently downloaded blocks via `zebra-network`. (We can't move the whole syncer due to crate dependencies.)

Instead, you could use a similar design to `ChainTip`:
- add a `SyncStatusTrait` to `zebra-chain` (after picking a better name!)
- keep the real implementation in `zebrad`, but turn `impl SyncStatus` into `impl SyncStatusTrait for SyncStatus`
- pass the real `SyncStatus` to `zebra-rpc` using a generic with a `SyncStatusTrait` bound

If needed:
- Add `FullySynced` and `StillSyncing` stub implementations to `zebra-chain` for testing

That way we can use `SyncStatus` in all our crates, not just the ones that depend on `zebra-network`.
