### ISSUE TITLE
transaction::tests::v4_with_modified_joinsplit_is_rejected fails with unexpected verifier error

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5823]
## Motivation

> ---- transaction::tests::v4_with_modified_joinsplit_is_rejected stdout ----
> 
> The application panicked (crashed).
> Message:  assertion failed: `(left == right)`
>   left: `Err(RedJubjub(InvalidSignature))`,
>  right: `Err(Groth16("proof verification failed"))`
> Location: zebra-consensus/src/transaction/tests.rs:1578

https://github.com/ZcashFoundation/zebra/actions/runs/3645234772/jobs/6155200323#step:14:1505

### Specifications

TODO: quote the relevant spec sections from https://zips.z.cash/

### Complex Code or Requirements

This looks like a race condition between the proof and signature verifier. (Modifying the proof makes the signature invalid.)

We can fix this failure by accepting either error.

### Testing

It's going to be tricky to test that any fix works correctly.

**Comment by conradoplg** [comment]
This is really baffling, I can't come up with a scenario where that happens. At first I thought the test could be changing the same transaction, but that's not it, since test_transactions deserializes blocks and thus returns fresh references each time.  The verifier is also freshly created each time.

**Comment by teor2345** [comment]
Happened once on macOS:
> Error is for macos only in the v4_with_modified_joinsplit_is_rejected test: https://github.com/ZcashFoundation/zebra/actions/runs/4068002665/jobs/7006036670#step:14:1929

https://github.com/ZcashFoundation/zebra/pull/6044#issuecomment-1412710691

**Comment by arya2** [comment]
> At first I thought the test could be changing the same transaction

The `async_checks` are unordered and the `verify_sapling_shielded_data` check may occasionally be faster.

I don't see it filtering out v5 transactions for the test so I wonder if it may be calling `verify_orchard_shielded_data` as well.

> Accept either error?

We could alternatively modify the signature when modifying the proof so only the proof verification check would fail if modifying the proof makes the signature invalid?

**Comment by teor2345** [comment]
> > At first I thought the test could be changing the same transaction
> 
> The `async_checks` are unordered and the `verify_sapling_shielded_data` check may occasionally be faster.
> 
> I don't see it filtering out v5 transactions for the test so I wonder if it may be calling `verify_orchard_shielded_data` as well.
> 
> > Accept either error?
> 
> We could alternatively modify the signature when modifying the proof so only the proof verification check would fail if modifying the proof makes the signature invalid?

Yep, either way would work, let's do whatever is faster?

**Comment by mpguerra** [comment]
How often is this happening? Can this wait until next sprint?

**Comment by teor2345** [comment]
> How often is this happening? Can this wait until next sprint?

If it is only happening once every few weeks, then I think this ticket could be closed as "not planned". Testing mining is a much higher priority right now.

@arya2 what do you think?

**Comment by arya2** [comment]
> @arya2 what do you think?

I agree, it's not happening very often, we can revisit this if that changes.

**Comment by teor2345** [comment]
This happened again in PR #6285 on the `main` branch:
https://github.com/ZcashFoundation/zebra/actions/runs/4378912467/jobs/7664245887#step:14:1930

**Comment by teor2345** [comment]
This happened in PR #6407:
https://github.com/ZcashFoundation/zebra/actions/runs/4516693112/jobs/7955277180?pr=6407#step:14:1398

Since it's happening about once a week, I think it's a low but not optional fix.

**Comment by mpguerra** [comment]
Tentatively scheduled this for next sprint (2023 Sprint 8)

**Comment by daira** [comment]
Yes, {JoinSplit, Spend, Output} proofs are included in the data hashed for all signatures in v4 transactions; see https://zips.z.cash/zip-0243#specification sections 6, 7, and 8.

({Spend, Output, Action} proofs are *not* included in the data hashed for signatures in v5 transactions: https://zips.z.cash/zip-0244#txid-digest )

**Comment by teor2345** [comment]
This failed merge queue PR #6511:
https://github.com/ZcashFoundation/zebra/actions/runs/4695369391/jobs/8324474256#step:14:11652

@mpguerra this seems like a bug we should fix, our current CI error rate is making it hard to merge PRs.

**Comment by teor2345** [comment]
The other test failures we're currently seeing seem to be happening more often.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5823?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
Failed in PR #6566:
https://github.com/ZcashFoundation/zebra/actions/runs/4801740662/jobs/8544342511?pr=6566#step:14:1411

**Comment by upbqdn** [comment]
Here's my summary:

We modify the proof here https://github.com/zcashfoundation/zebra/blob/58bd898f5be362d7c67f8ba36eeac172482f4072/zebra-consensus/src/transaction/tests.rs#L1931. As already pointed out, this altered data is then hashed here https://github.com/zcashfoundation/zebra/blob/58bd898f5be362d7c67f8ba36eeac172482f4072/zebra-consensus/src/transaction.rs#L629, which makes the resulting sighash invalid when Zebra checks the tx signatures against it. The proof and signatures are checked concurrently, and the bug shows up when the signature check finishes first. It seems there are also checks on Ed25519 against the invalid sighash, which should also fail, and it's interesting these have never shown up in the logs. It's only been RedJubJub sigs. I guess Ed25519 might be slower. 

> We could alternatively modify the signature when modifying the proof so only the proof verification check would fail if modifying the proof makes the signature invalid?

Since the tx comes from real blocks, we don't have the original keys. I'm now briefly checking if we could use made-up keys and regenerate the tx sigs for the test. If not, I'll try to run the test in a loop with a constant threshold until it passes and see if a loop would make the test much slower. If yes, I guess we'll just have to accept a wrong signature as the correct outcome of the test.

**Comment by teor2345** [comment]
This bug is still not fixed, unfortunately:
> ---- transaction::tests::v4_with_modified_joinsplit_is_rejected stdout ----
> The application panicked (crashed).
> Message:  assertion failed: `(left == right)`
>   left: `Err(InternalDowncastError("downcast to known transaction error type failed, original error: InvalidSignature"))`,
>  right: `Err(Groth16("proof verification failed"))`
> Location: zebra-consensus/src/transaction/tests.rs:2163

https://github.com/ZcashFoundation/zebra/actions/runs/5225593214/jobs/9435269099?pr=6878#step:10:1321

We could increase the number of test cases, or accept either error as correct.
