### ISSUE TITLE
CI : docker - failed to copy - connection reset by peer

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#5869]
I am seeing this error in a merged pull request into main:

https://github.com/ZcashFoundation/zebra/actions/runs/3699928299/jobs/6267824590#step:9:2107

Happened after https://github.com/ZcashFoundation/zebra/pull/5864 was merged.

Unsure if we already have a ticket for it.

**Comment by teor2345** [comment]
This seems to be a temporary network failure, but I'd like @gustavovalverde to double-check.

There are also warnings about missing documentation, but they aren't errors, and they aren't related to this particular connection error. It might be nice to fix them to avoid confusion when diagnosing Docker bugs.

**Comment by gustavovalverde** [comment]
After a bit of research here, even though it is a network failure issue I tried to find ways to "increase" the retry time, but there's a exponential retry mechanism built-in into `buildkit` which we can't modify with arguments https://github.com/moby/buildkit/pull/1791/files#diff-682011b3dfc5c45f6d422e716e452cc9c7e147a3808c94662473bffd7ad49995R16 and it got triggered in the action.

Sometimes this also fails if there's an issue with the cache (which I had to workaround a few months ago), but this is a known issue which we'll have to wait for it to be fixed https://github.com/moby/buildkit/issues/2578 

In any case, this is temporal and we might won't plan to "fix it". Feel free to re-open it if you understand otherwise.

**Comment by mpguerra** [comment]
@gustavovalverde can you please add a size estimate here based on your investigations?

**Comment by teor2345** [comment]
Thanks for looking into this!
