### ISSUE TITLE
ci: migrate actions using the unmaintained `actions-rs/*` repository

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#6048]
## Motivation

We might have to stop using `actions-rs/toolchain` and `actions-rs/cargo` as those actions are no longer maintained, and might break sooner or later based on existing warnings:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1.0.3
```

## Related Work

https://github.com/ZcashFoundation/zebra/pull/6039

**Comment by teor2345** [comment]
We could fork the repositories and apply these fix PRs:
https://github.com/actions-rs/toolchain/pull/224
https://github.com/actions-rs/cargo/pull/223
https://github.com/actions-rs/tarpaulin/pull/22

But if we're going to do that, let's wait until March or April?
The original repositories might end up being fixed in the meantime.

**Comment by mpguerra** [comment]
un-scheduling for now

**Comment by mpguerra** [comment]
Seems like some of this may be dealt with in this blog post: https://blog.urth.org/2023/03/05/cross-compiling-rust-projects-in-github-actions/
