### ISSUE TITLE
Consider downgrading `owo-colors` crate?

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#6197]
When i follow[ this instructions ](https://zebra.zfnd.org/user/lightwalletd.html#download-and-build-zebra)to install zebra i get the following warning:

```
$ cargo install --locked --git https://github.com/ZcashFoundation/zebra zebrad
    Updating git repository `https://github.com/ZcashFoundation/zebra`
  Installing zebrad v1.0.0-rc.4 (https://github.com/ZcashFoundation/zebra#4daedbc7)
    Updating crates.io index
warning: package `owo-colors v3.6.0` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
...
```

Version seems to be yanked by the author: https://crates.io/crates/owo-colors/versions

Should we downgrade to `3.5.0` ?

**Comment by teor2345** [comment]
It was yanked due to a breaking change which causes a compilation error in some APIs that we don't use:
https://github.com/jam1garner/owo-colors/issues/82

But I agree we should fix the usability issue.

Let's fix it before the next release and before miners test Zebra?
(Because they might spend time tracking down the yanked crate, or might avoid Zebra because yanked crates often mean security issues.)

@mpguerra can we do this very quick ticket this week?

**Comment by mpguerra** [comment]
> @mpguerra can we do this very quick ticket this week?

Sure, @teor2345 can you please add an estimate for it?
