### ISSUE TITLE
Design: Script implementation in Rust

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#621]
We should have a design document for this.

**Comment by hdevalence** [comment]
This is a fragment but I think a nice way to do zero-copy script parsing and execution is to create an `Op` enum whose variants correspond to script operations (note: this correspondence does not need to be exact, see below), and implement parsing as an iterator of `Op`s.  These ops can then be fed into something that executes the script.

Having zero-copy script parsing and execution would be nice because instead of special-casing P2SH or P2PK scripts with a fast path, we could just execute all scripts quickly.

Some scratch work: if we have 
```rust
struct Script(Vec<u8>);

enum Op { /* ... */ }
```
then we could have
```rust
struct ScriptIterator<'s>(&'s [u8]);
impl<'s> Iterator for ScriptIterator<'s> {
    type Item = Op;
    fn next(&mut self) -> Op {
        if let Some(opcode, mut rest) = self.0.split_first() {
            let op = match opcode {
                 // do stuff, potentially splitting more data out of `rest`
            }
            self.0 = rest;
            Some(op)
        } else {
            None
        }
   }
}

impl Script {
    fn ops(&'s self) -> ScriptIterator<'s> {
        ScriptIterator(&self.0[..])
    }
}
```
Here the `ScriptIterator` uses the slice to keep track of where it is in the encoded script data, and the `'s` lifetime bound binds the lifetime of the `ScriptIterator` to the parent `Script` (the iterator cannot outlive the data it refers to). Calls to `next()` can be inlined, so that each `Op` is generated right where it will be used for execution and kept on the stack or in registers.

This isn't quite right, though, because some operations (like pushdata) refer to bundled data, and it would be good to avoid copying that data, too.  But this can be fixed up by adding a lifetime bound to the `Op` enum:
```rust
enum Op<'s> {
    PushData(&'s [u8]),
    // ...
}

impl<'s> Iterator for ScriptIterator<'s> {
    type Item = Op<'s>;
    fn next(&mut self) -> Op<'s> {
        // now subslices of self.0 can be included in the returned Op
    }
}
```
Notice that even though Bitcoin Script has three pushdata opcodes (`OP_PUSHDATA1`, `OP_PUSHDATA2`, `OP_PUSHDATA4`), it's not necessary to have three separate `Op` variants, since the slice used to track the data to be pushed already includes the length.  Similarly, it's not necessary to have separate variants for `OP_2-OP_16`, since these can all be represented by a single variant holding the integer.

This is a nice start but it doesn't handle branching control flow.

**Comment by dconnolly** [comment]
Closing as we are using `zcash_script` for now
