### ISSUE TITLE
Limit the number of queued blocks at each height

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#628]
To avoid a memory DoS, we want to limit the number of queued blocks at each height:
https://mobile.twitter.com/_prestwich/status/1281325791297470464

- [x] Any additional blocks should fail validation immediately.

Assuming we checkpoint every 500 blocks, the maximum memory usage for a checkpoint range is:
* 1 block per height: `1 * 2 MB * 500 = 1 GB`
* 2 blocks per height: `2 * 2 MB * 500 = 2 GB`
* 3 blocks per height: `3 * 2 MB * 500 = 3 GB`

When we're close to having a full range, the queue might contain some blocks from the next range as well. So the actual usage is slightly higher.

On my machine, `zcashd` uses approximately 1-3 GB, so we should try to restrict checkpoint memory usage to 1-2 GB. 

We could remove the `QueuedBlockList` vector, and just accept 1 block per height. But if we got a bad block, we would have to wait for the sync service to re-fetch the correct block.

To avoid quadratic behaviour on multiple bad blocks, we should:
- [ ] ~discard all the unverified blocks in the interval~ - not implemented, because rejecting blocks lower than the bad block makes other attacks possible

This change resists an attack where a single bad peer feeds us multiple bad blocks, then we reject a bad block, restart the sync service, wait for downloads, re-fetch a good block, then find another bad block lower down...

Let's also keep up to 2 blocks per height, so we can efficiently reject blocks from a single bad peer:
- [x] 2 blocks per height: `2 * 2 MB * 500 = 2 GB`

Since `QueuedBlockList` is `Vec<Arc<Block>>`, and `Block` is `{header: BlockHeader, transactions: Vec<Transactions>}`, the actual size of empty allocations is only ~1.4 kB for the block header and a few pointers.

So we don't need to carefully manage vector capacity with each `push`. We can just:
- [x] initialise vectors `with_capacity(2)` - the maximum number of blocks at each height

We won't need to use `reserve_exact` or `shrink_to_fit`. (And in any case, we `drain` vectors during validation, and only re-queue valid blocks.)

**Comment by hdevalence** [comment]
Just to clarify: should this issue title be "Limit the number of queued blocks at each height"?

**Comment by teor2345** [comment]
Oops!

**Comment by hdevalence** [comment]
I don't think that this attack is practical. Because we randomize block hash requests and block download requests over the available peers, the ability of any single peer or collection of peers to feed us bad blocks is limited. In order for this to happen, we have to first request a list of hashes, and that request to be routed to an evil peer.  Then, we split those hashes into chunks and attempt to download those chunks. Those download requests also have to be routed to evil peers, since honest peers won't have those blocks.  For this to happen, we need a significant number or possibly a majority of our peers to be malicious, at which point we're already in serious trouble.  So to be more precise, it's not exactly that this attack is impractical, but that the conditions under which it is practical imply worse things.

However, if we do want to be extra resilient against this threat, I think that there is an easier low-effort mitigation: checking the proof of work of each incoming block immediately.  This check can be done statelessly and forces any adversary to not just control a majority of our peers but to spend a significant amount of proof-of-work.
