### ISSUE TITLE
[NCC-E005955-DBV] `zebra-chain`: Unbounded Rejection Sampling with Possibility of Panics

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6338]
## Impact

The `zebra-chain` module implements random number generation for some types which are primarily used for testing, without guarding against possible panics.

## Description

The use of `fill_bytes()` in the code snippet below (from `zebra-chain/src/sapling/keys.rs`) [can potentially cause panics](https://docs.rs/rand/latest/rand/trait.RngCore.html#tymethod.fill_bytes). It is recommended to use `try_fill_bytes()` to catch the random number generator’s failures<sup>1</sup>.

In addition, the number of sampling retries by the loop has to be bounded.

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-chain/src/sapling/keys.rs#L176-L196

There is one instance where this can potentially be problematic for a full node with mining support. Generating [a random](https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-chain/src/orchard/note.rs#L65) `Rho` for an Orchard note uses the same unchecked RNG API.

A node with mining capabilities might use this API to generate [a dummy Orchard input note](https://zips.z.cash/protocol/nu5.pdf#orcharddummynotes) as a nullifier for the output note when creating a miner’s reward note:

https://github.com/ZcashFoundation/zebra/blob/161bb80ce8fc131bd7fea3a95723b34f1795716e/zebra-chain/src/orchard/note.rs#L59-L69

---
1. For instance `OsRng` can, in rare occasions, fail on some platforms, and `thread_rng` might return a
warning if it fails to reseed itself. See https://rust-random.github.io/book/guide-err.html for more
details.
## Recommendation

Consider replacing the `fill_bytes()` usage with `try_fill_bytes()` and properly handle its possible failure.

## Location

- [zebra-chain/src/orchard/keys.rs, line 110](https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-chain/src/orchard/keys.rs#L110)
- [zebra-chain/src/sapling/keys.rs, line 189](https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-chain/src/sapling/keys.rs#L189)
- [zebra-chain/src/orchard/commitment.rs, line 30](https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-chain/src/orchard/commitment.rs#L30)
- [zebra-chain/src/sapling/commitment.rs, line 42](https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-chain/src/sapling/commitment.rs#L42)
- [zebra-chain/src/orchard/note.rs, line 30](https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-chain/src/orchard/note.rs#L30)
- [zebra-chain/src/orchard/note.rs, line 65](https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-chain/src/orchard/note.rs#L65)

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6338?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This doesn't block starting work on Orchard shielded coinbase mining, but it does block running on mainnet.

**Comment by daira** [comment]
The documentation of when `fill_bytes` can panic (which is documented to be exactly when `try_fill_bytes` can return an error) does not convince me that zebra shouldn't actually panic in this situation:

> This method should guarantee that `dest` is entirely filled with new data, and may panic if this is impossible (e.g. reading past the end of a file that is being used as the source of randomness).

We shouldn't read a file to get randomness, or anything similarly unreliable, for a cryptographic RNG. Note that this method is defined on `RngCore`, and the design of the `rand` crate makes `CryptoRng` just a marker trait, so it can't change the API. But it's likely that the design of `RngCore` was intended to allow a wide variety of possible sources of randomness that are not necessarily cryptographic, and that informed the error handling in ways that are less than ideal for a cryptographic RNG.

The Zcash protocols assume that it is always possible to get randomness. If an RNG returns an error, then either:
* The RNG is always going to fail for the rest of this process execution. In that case the process can't reasonably continue, since it's going to need randomness very frequently and there aren't many useful things it can do without it. Since zebra is designed to tolerate crashes, the best thing to do is to crash immediately.
* The failure is intermittent. In that case, how do we know that it isn't correlated with the output that the RNG would have returned? If it is, then that potentially biases future output. So again zebra should crash, in order to minimize the damage and make sure that the user knows something is seriously wrong.
* The failure could be a symptom of something else, like memory corruption / undefined behaviour. Again zebra should crash to minimize possible damage.

**Comment by dconnolly** [comment]
> The documentation of when `fill_bytes` can panic (which is documented to be exactly when `try_fill_bytes` can return an error) does not convince me that zebra shouldn't actually panic in this situation:
> 
> > This method should guarantee that `dest` is entirely filled with new data, and may panic if this is impossible (e.g. reading past the end of a file that is being used as the source of randomness).
> 
> We shouldn't read a file to get randomness, or anything similarly unreliable, for a cryptographic RNG. Note that this method is defined on `RngCore`, and the design of the `rand` crate makes `CryptoRng` just a marker trait, so it can't change the API. But it's likely that the design of `RngCore` was intended to allow a wide variety of possible sources of randomness that are not necessarily cryptographic, and that informed the error handling in ways that are less than ideal for a cryptographic RNG.
> 
> The Zcash protocols assume that it is always possible to get randomness. If an RNG returns an error, then either:
> 
> * The RNG is always going to fail for the rest of this process execution. In that case the process can't reasonably continue, since it's going to need randomness very frequently and there aren't many useful things it can do without it. Since zebra is designed to tolerate crashes, the best thing to do is to crash immediately.
> * The failure is intermittent. In that case, how do we know that it isn't correlated with the output that the RNG would have returned? If it is, then that potentially biases future output. So again zebra should crash, in order to minimize the damage and make sure that the user knows something is seriously wrong.
> * The failure could be a symptom of something else, like memory corruption / undefined behaviour. Again zebra should crash to minimize possible damage.

All of these sources of randomness are happening in a library, which in general terms should not panic, but raise an error. The consumer of the library should determine their behavior on catching such an error, such as panic, for example if they are a wallet. We don't have a wallet yet. If `zebrad` is generating `Rho`'s for Orchard notes for mining, or generating note commitments, we should catch the error at the application level and panic, but I don't think we are doing that yet: we are generating block templates that miners use. For shielded coinbase (Sapling and Orchard), we (`zebrad` / `zebra-consensus`, the consumer of `zebra-chain`) will catch any of these errors and _then_ panic.

**Comment by mpguerra** [comment]
Can we document this in the code for future use cases?

**Comment by daira** [comment]
> All of these sources of randomness are happening in a library, which in general terms should not panic, but raise an error. The consumer of the library should determine their behavior on catching such an error, such as panic, for example if they are a wallet. We don't have a wallet yet. If zebrad is generating Rho's for Orchard notes for mining, or generating note commitments, we should catch the error at the application level and panic, but I don't think we are doing that yet: we are generating block templates that miners use. For shielded coinbase (Sapling and Orchard), we (zebrad / zebra-consensus, the consumer of zebra-chain) will catch any of these errors and then panic.

I disagree, and I've told you my considered professional opinion as a cryptographic engineer. The auditors are wrong, and a panic is the appropriate behaviour. It does not matter whether the panic happens at the library or application layer, except that the latter has slightly greater risk of the panic not actually happening, or of there being negative consequences of undefined behaviour if the failure is due to that.

(If zebra didn't follow crash-only design, it might be appropriate to do a controlled shutdown that flushes data to disk for example. But it does, so that argument doesn't apply.)

**Comment by teor2345** [comment]
> (If zebra didn't follow crash-only design, it might be appropriate to do a controlled shutdown that flushes data to disk for example. But it does, so that argument doesn't apply.)

At this point a controlled shutdown isn't required in Zebra, because we commit each verified block to disk in a database transaction. So either the transaction commits and the database is valid with the new block, or it is rolled back on restart and it's valid with the old block. Losing a block doesn't matter, because we drop the last 100 blocks in memory every time we restart anyway.

This would be different if we had a wallet, or any other kind of non-transactional persistent data. In that case, we'd probably want to do an atomic switch to the new version of the file (or directory):
https://users.rust-lang.org/t/how-to-write-replace-files-atomically/42821
https://docs.rs/atomicwrites/latest/atomicwrites/struct.AtomicFile.html#method.new

**Comment by teor2345** [comment]
(This is just for info, it's not related to the specific decision about cryptographic panics.)
