### ISSUE TITLE
can_fork_chain_at() should ignore blocks below the finalized tip

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6388]
## Motivation

We can't fork the chain at a finalized block height below the finalized tip height, but the `sent_non_finalized_blocks` data structure contains the heights of some finalized blocks close to the final checkpoint.

We might need to store the queued finalized block list separately, rather than re-using an existing data structure that other code depends on.

(This is an existing bug, but the code in the linked audit PR added more finalized blocks to the data structure.)

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/pull/6335#discussion_r1144234829_

## Scheduling

We reviewed this code, and checked that even if it was called incorrectly, the write block task would return a similar error. So this is just a technical debt cleanup.

**Comment by mpguerra** [comment]
Whilst it seems like we want to fix it, I don't think we should classify this as an audit fix... 

The reason why we were working on #6335 to close #862 was not because #862 was identified as a potential issue from the audit. Instead, #862 was flagged as an issue that was mentioned in a `TODO` comment but was closed, potentially making the `TODO` comment redundant... 

We should finish off #6335 and #862 since we have already started work on them, however I would like to prioritise actual audit issues first and fix these other items before a stable release.

**Comment by teor2345** [comment]
I just checked the code that validates and writes non-finalized blocks, it will correctly return a NotReadyToBeCommitted error without panicking, even if it sends a block based on these incorrect block hashes. So this is mainly a performance and maintainability issue.

The code that writes finalized blocks ignores the incorrect block hashes, it just uses a single most recently sent hash.

**Comment by teor2345** [comment]
We've actually seen this issue in production, so this is a medium priority.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6388?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
I just remembered that we reviewed this code, and checked that even if it was called incorrectly, the write block task would return a similar error.

So @Pili I don't think it's a blocker for the stable release at all, and I think it's actually a low priority.
