### ISSUE TITLE
Show that duplicate nullifier errors are propagated through the transaction verifier

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#6399]
There are currently no tests to check that duplicate nullifier errors from the state are being propagated through the transaction verifier correctly.

~But since our error handling is generic, we don't need to write new tests, we can just point to existing tests that together cover this kind of error handling.~

We are missing test coverage for error conversions from zebra-state to zebra-consensus.

**Comment by teor2345** [comment]
I think we can respond to this issue by finding existing tests that cover this kind of error handling.

For example:
- unit tests for duplicate nullifier errors
- integration tests for any state errors in mempool transaction validation or block validation
    - a good example would be submit block or block proposal RPC errors
- full `zebrad` integration tests that run the syncer and inbound block verify services, occasionally encounter errors, and handle them correctly

Since most of our error handling doesn't consider the specific type of error, this should be enough to show that nullifier errors are handled correctly.

**Comment by mpguerra** [comment]
Is this related to #6338 ? Or a different audit issue

**Comment by arya2** [comment]
> Is this related to #6338 ? Or a different audit issue

This is a different issue that wasn't in the findings but was brought up during the audit sync.

**Comment by teor2345** [comment]
@arya2 we think you might be the best person to do this ticket?

**Comment by arya2** [comment]
`mempool_request_with_immature_spent_is_rejected` checks that `ValidateContextError`s are converted correctly, though it doesn't check downcasts from BoxErrors so we may want to add a test for that.

https://github.com/ZcashFoundation/zebra/blob/8a9113c4e2fc3cd551f5cf94c3b8177591a54eae/zebra-consensus/src/transaction/tests.rs#L611-L662

**Comment by teor2345** [comment]
> though it doesn't check downcasts from BoxErrors so we may want to add a test for that.

Seems like it might be a low priority, but that's @dconnolly's call.

**Comment by mpguerra** [comment]
@arya2 what's the complexity of this fix and what would be the effort required to address this audit comment? Do we need to review the issue estimate? Feel free to update it to what you think is a more accurate reflection of the size of this issue.

**Comment by arya2** [comment]
> what's the complexity of this fix and what would be the effort required to address this audit comment? Do we need to review the issue estimate? Feel free to update it to what you think is a more accurate reflection of the size of this issue.

The estimate is still accurate.
