### ISSUE TITLE
Create a checkpoint backpressure design that favours lower height blocks

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#642]
The checkpoint queue memory limits in #640 are a hard limit that keeps our memory usage from blowing out.

But we'd like to use backpressure to slow down block downloads. Ideally, we want a backpressure design with the following properties:
* favours lower block heights, so checkpoint ranges can validate and get written to disk
* keeps memory usage reasonable:
  * dynamically detects available memory (if possible)
  * a documented, low default that allows at least one checkpoint range to validate, even under memory DoS (2 GB)
  * a config option that allows the default to be increased (for faster syncing, or to resist memory DoS)

Tower's backpressure design doesn't really support this use case, because its backpressure would stop all the block downloads. But we want to stop downloading high blocks, and continue downloading low blocks.

This change might not be required in our initial release, as long as the hard limits are good enough. But we might need it for robust syncing.

**Comment by hdevalence** [comment]
Since we already have (or will have, once I finish #617) backpressure in the syncer that decides which blocks to download and manages downloading, do we need to have backpressure in the verifier component?

I'm not sure that it makes sense to have backpressure in the checkpoint verifier, because the checkpoint verifier is a service that operates on `Block`s.  By the time a verification request is being made to the checkpoint verifier, the block is already downloaded. So having the verifier exert backpressure on verification requests can't help manage downloads.  Moreover, it would mean that instead of having the block download logic be the responsibility of the syncer and verification be the responsibility of the verifier, they would need to share responsibility.

On the other hand, as long as the syncer handles backpressure correctly (#617), the verifier doesn't need to do anything special, because the syncer is responsible for not downloading too many blocks at once.

I also don't think that the memory DoS concern is worth trying to defend against in the checkpoint verifier, because it's already defended against in the syncer design (cf https://github.com/ZcashFoundation/zebra/issues/628#issuecomment-657781665).

**Comment by teor2345** [comment]
Great, I'll close this ticket as obsolete.
