### ISSUE TITLE
Move CI coverage to larger GitHub Actions runners

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#6457]
## Motivation

There are a lot of units tests that can take a while to run on hosted runners with 2-3 cpu cores and produce large log outputs for developers to sift through when something fails.

Splitting up coverage tests by crate will:
- hint at which category of tests failed without developers needing to look at the logs,
- produce smaller logs to examine when there's a failure
- speed up coverage tests

**Comment by teor2345** [comment]
Our other options are:
- deleting these duplicate tests in GitHub Actions, and just running them in Google Cloud (this depends on getting Google Cloud running correctly in the private Zebra repository)
- downgrading, disabling, or rate-limiting verbose logs, seems like the info-level block proposal log is very verbose in tests

**Comment by mpguerra** [comment]
@gustavovalverde this is something to take into consideration as we look to make changes to our CI

**Comment by teor2345** [comment]
@mpguerra I think the solution in this ticket will be very difficult technically, because we need to combine the coverage output files from all the tests to get an overall coverage score. This is hard to do when they are running on different machines.

We would also need to do this on the `main` branch to get a base coverage score.

Instead, I suggest we open a new ticket to do one of these things:
- move coverage to larger GitHub Actions runners, this should be a very quick change
- move coverage from GitHub Actions to Google Cloud
