### ISSUE TITLE
Remove the block::header::EquihashError type

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#658]
non-blocking on this PR, but just something I noticed: I think we might be able to get rid of this error type entirely, since serialization is infallible mod the underlying writer, and presumably the verification code serializes into a `Vec` (which shouldn't fail except by OOM).

_Originally posted by @hdevalence in https://github.com/ZcashFoundation/zebra/pull/631_

**Comment by teor2345** [comment]
@yaahc what do you think?

**Comment by yaahc** [comment]
sounds good to me

**Comment by yaahc** [comment]
I opened a PR to fix this, I don't think we should remove the `EquihashError` type entirely because the errors we get from the equihash crate are very specific to why the solution was not valid, but without context I expect the errors to make little sense

```rust
impl fmt::Display for Kind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Kind::InvalidParams => f.write_str("invalid parameters"),
            Kind::Collision => f.write_str("invalid collision length between StepRows"),
            Kind::OutOfOrder => f.write_str("Index tree incorrectly ordered"),
            Kind::DuplicateIdxs => f.write_str("duplicate indices"),
            Kind::NonZeroRootHash => f.write_str("root hash of tree is non-zero"),
        }
    }
}
```

By keeping the `EquihashError` type but making it a wrapper around the existing error kind we end up with error messages like "invalid equihash solution for BlockHeader: root hash of tree is non-zero" instead of just "root hash of tree is non-zero". And because its no longer an enum we don't have a tag and the `EquihashError` struct ends up being the same size as the underlying `equihash::Error`.
