### ISSUE TITLE
Execute Zebra full sync weekly on the `main` branch

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#6631]
### Discussed in https://github.com/ZcashFoundation/zebra/discussions/6603

<div type='discussions-op-text'>

<sup>Originally posted by **gustavovalverde** May  3, 2023</sup>
GitHub changed the behavior of the concurrency, showing cancellation statuses as failures, rather than ignoring them and showing it as successes. Having all those :x: in the main branch is confusing, and we should decide how to handle this situation.

We have several options (including others not listed here):
- Not running the full sync on each merge, as we're anyways cancelling those until a previous one finishes
- Have it on its own workflow and have a more specific decision tree on when to trigger it
- Schedule it to run twice a week or weekly (as it anyways takes 3+ days to complete)
- Having a trigger on the PR, as we might want to validate if a critical PR runs a Full sync safely before merging it (required check for specific labels [?])</div>

**Comment by teor2345** [comment]
Whatever we do here, it should probably apply to:
- zebra full mainnet sync
- lightwalletd full mainnet sync (which depends on the zebra sync)
- zebra full testnet sync

There is also a zebra checkpoint mainnet sync, it only runs when the state version changes, or we migrate to a new environment.

> We have several options (including others not listed here):
> * Not running the full sync on each merge, as we're anyways cancelling those until a previous one finishes

This seems like a good idea.

> * Have it on its own workflow and have a more specific decision tree on when to trigger it

This might be tricky, because the jobs that depends on full syncs need to wait until it runs. (This only happens when we update our state version, move to a new CI environment, or delete all our cached states manually.)

> * Schedule it to run twice a week or weekly (as it anyways takes 3+ days to complete)

I think once a week would be fine, on a Friday so the results are ready to check before the engineering sync.

> * Having a trigger on the PR, as we might want to validate if a critical PR runs a Full sync safely before merging it (required check for specific labels [?])

We can already manually run these syncs using workflow dispatch, I don't think we do it often enough to make it worth using labels or any other automated tasks.
