### ISSUE TITLE
Remove duplicate dependencies from `deny.toml` once `ed25519-zebra` and `zcashd` are released

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6638]
## Motivation

We want to remove as many duplicate dependencies as possible from the zebra codebase. This should be possible after https://github.com/zcash/zcash/issues/6648 currently planned for the the `zcashd` 5.6.0 release.

### Specifications

With the `zcashd` 5.6.0 release, we we can upgrade and delete these dependencies in `deny.toml`

https://github.com/ZcashFoundation/zebra/blob/39c599713abce08654de30a4f99c2bdcb69a21b1/deny.toml#L71-L74

https://github.com/ZcashFoundation/zebra/blob/39c599713abce08654de30a4f99c2bdcb69a21b1/deny.toml#L85-L89

https://github.com/ZcashFoundation/zebra/blob/39c599713abce08654de30a4f99c2bdcb69a21b1/deny.toml#L96-L97

https://github.com/ZcashFoundation/zebra/blob/39c599713abce08654de30a4f99c2bdcb69a21b1/deny.toml#L76-L78

https://github.com/ZcashFoundation/zebra/blob/4b6e2fe2236956d32102bddf74a979cb97fbf095/deny.toml#L64-L65

## Related Work

- #6624 
- https://github.com/zcash/zcash/issues/6648 
- https://github.com/ZcashFoundation/ed25519-zebra/issues/79

**Comment by teor2345** [comment]
@mpguerra the next step here is to publish an ed25519-zebra release. The updated dependencies are in its main branch, but they haven't been released yet.

Once ed25519-zebra is done, it should be automatically picked up by the zcashd and zcash_script release processes. Then Zebra will pick it up automatically using dependabot.

Just a note: the deny.toml entries linked in the ticket will be outdated by the time we do this ticket, because PR #6624 will modify them.

(This ticket is also related to https://github.com/ZcashFoundation/ed25519-zebra/issues/77 , because the release instructions for all our crates should include updating dependencies.)

**Comment by daira** [comment]
Note that we are cutting an rc of zcashd, so this is at risk of not getting into zcashd 5.6.0 if it is not done very soon.

**Comment by mpguerra** [comment]
tentatively scheduling for next sprint

**Comment by teor2345** [comment]
This needs to be done as part of #6859, can we close this ticket and just make it part of the PR for #6959?

(The duplicate dependency tests don't look for extra allowed duplicates, only new duplicates. So it needs to be a manual change as part of the dependency update.)

**Comment by teor2345** [comment]
I'm going to close this as incomplete rather than trying to track its dependencies separately, because it should happen in the same PR as #6859.

**Comment by teor2345** [comment]
Splitting this out of #6859
