### ISSUE TITLE
Send tracing output to stderr

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#667]
We want to modify Zebra's `Tracing` component to accept a generic writer type with a `MakeWriter` bound. Then we can redirect all tracing output to stderr.

This is an important change for unix-based OSes, because it lets users separate logging output from actual command output. (Currently, Zebra's non-server commands use stdout to provide results or usage messages.)

For details, see:

The Zebra workaround:
  * https://github.com/ZcashFoundation/zebra/blob/main/zebrad/src/application.rs#L132

tracing_subscriber:
  * Formatter: https://docs.rs/tracing-subscriber/0.2.5/src/tracing_subscriber/fmt/mod.rs.html#164-168
  * fmt_layer::Layer: https://docs.rs/tracing-subscriber/0.2.7/src/tracing_subscriber/fmt/fmt_layer.rs.html#61-72
  * MakeWriter bound: https://docs.rs/tracing-subscriber/0.2.7/src/tracing_subscriber/fmt/fmt_layer.rs.html#108

**Comment by hdevalence** [comment]
#561 seems potentially related, in that both of these issues are about managing how the `tracing` `Subscriber` is configured.  It seems like a common pain point is difficulty configuring the subscriber used by Abscissa.

**Comment by teor2345** [comment]
This is now possible after #834, because we have our own Tracing component now.

**Comment by hdevalence** [comment]
It seems like there are two distinct cases where this might come up:

1. In commands like `help`, `version`, `generate`, etc, we don't want to intermingle the output of the command with a bunch of extraneous messages.  But switching the output to `stderr` doesn't really help with that, because by default both streams are written to the terminal.  So, if emit any extraneous messages, users will still have problems by default (which we don't want), and if we don't emit any extraneous messages, there's no problem regardless of where we put them.

2. When running server commands like `start`, `seed`, etc., it might be useful to be able to capture tracing information and store it somewhere.  But I think that using `stderr` is a bad solution to this problem, and a better one looks like integration with journald, opentelemetry, etc.  In this case, arguably the tracing events *are* the output of the program.

So because of (1) I'm not sure that switching to `stderr` really helps us solve a problem.  If we have to have people do `zebrad help 2>/dev/null` or whatever I think we've already failed, and if we haven't, I'm not sure we need to.

**Comment by teor2345** [comment]
> It seems like there are two distinct cases where this might come up:
> 
> 1. In commands like `help`, `version`, `generate`, etc, we don't want to intermingle the output of the command with a bunch of extraneous messages.  But switching the output to `stderr` doesn't really help with that, because by default both streams are written to the terminal.  So, if emit any extraneous messages, users will still have problems by default (which we don't want), and if we don't emit any extraneous messages, there's no problem regardless of where we put them.

I agree that:
  - there's not much point in separating output for `help`, because it is almost always read on a terminal,
  - if we never had any logs, it wouldn't matter if they went to stdout or stderr, and
  - in some cases, even if we do have logs, it doesn't matter if they go to stdout or stderr.

So let's try to focus on the cases where it does matter:

If we have unexpected log output, here are some use cases where logging to stderr is helpful:
```bash
zebrad generate > zebrad.toml

zebrad revhex "f000" > hex.txt
zcash-cli ... | jq ... | zebrad revhex > hex.txt

zebrad version | command-that-checks-version
```

In each of these cases, we should use stderr for logs. Then, if there are unexpected warning or error logs on stderr, they go to the terminal. But the intended output of the command is on stdout, and it goes to a file (or pipe).

> 2. When running server commands like `start`, `seed`, etc., it might be useful to be able to capture tracing information and store it somewhere.  But I think that using `stderr` is a bad solution to this problem, and a better one looks like integration with journald, opentelemetry, etc.  In this case, arguably the tracing events _are_ the output of the program.

I agree that:
- for people who are using better solutions, it doesn't matter if we use stdout or stderr.

Also, some process launchers will capture both stdout and stderr.

So let's try to focus on the cases where it does matter:
- some process launchers only capture stderr, and
- some developers and embedders will expect log output on stderr.

You're right that it often doesn't matter. But when it does matter, logs go to stderr.

**Comment by teor2345** [comment]
I think our workarounds are good enough here - I'm not sure we need to send logs to stderr any time soon.

**Comment by teor2345** [comment]
In fact, we're about to remove the revhex command in #1031, and we have acceptance tests that make sure that the generate stdout is parseable. (And doesn't contain logs.)

So I don't think we need to do this at all.
