### ISSUE TITLE
A fresh zebrad instance tries to verify the highest block

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#697]
As far as I understand, the sync service and block downloader should download blocks roughly in chain order. But I'm seeing `zebrad` download the tip of the current chain within a minute or two of starting.

Either our assumptions about zcashd are wrong, or zebrad has a bug:
- [ ] the sync service queries blocks from genesis onwards
- [ ] peers respond with hashes based on our queries
- [ ] the downloader rejects blocks that we haven't asked for

I'll try to make a branch and add diagnostic logs.

**Comment by teor2345** [comment]
I'm using the branch in PR #699.

The diagnostic warning is "unexpected high block".

**Comment by daira** [comment]
I haven't looked in detail, but I think the mistaken assumption may be "peers respond with hashes based on our queries". Peers can, and do, send unsolicited messages at any time. (I know, it sucks.)

**Comment by hdevalence** [comment]
@daira Something like that is probably the cause, but zebra-network doesn't make that assumption. Instead it's designed with the assumption that peers may send totally unrelated messages and goes to some effort to interpret whether any of the messages it sees are potential responses, so that the caller gets high quality responses (for instance, when you request a block, it checks that the block received is actually the block requested).

So this sounds like a bug where that interpretation and filtering logic is breaking down, not a bug where we're making a bad assumption about the network behavior.

**Comment by teor2345** [comment]
@hdevalence I don't think the sync service rejects high block hashes, and I'm not sure if it can.

So I think:
* zebrad::sync is getting a high hash from a peer, and then downloading it, or
* zebra-network is getting an unsolicited high block from a peer, and returning it to the syncer.

**Comment by hdevalence** [comment]
From https://en.bitcoin.it/wiki/Protocol_documentation#getblocks , the response to a `getblocks` message is an `inv` message with the hashes of the following blocks.  However, `inv` messages are also sent unsolicited to gossip new blocks across the network.  Normally, this wouldn't be a problem, because for every other request we filter only for the messages that are relevant to us.  But because the response to a `getblocks` message is an `inv`, the network layer doesn't (and can't) distinguish between the response `inv` and the unsolicited `inv`.

But there is a mitigation we can do.  In our sync algorithm we have two phases: (1) "ObtainTips" to get a set of tips to chase down, (2) repeatedly call "ExtendTips" to extend those as far as possible.  The unsolicited `inv` messages have length 1, but when extending tips we expect to get more than one hash.  So we could reject responses in ExtendTips that have length 1 in order to ignore these messages.  This way we automatically ignore gossip messages during initial block sync (while we're extending a tip) but we don't ignore length-1 responses while trying to obtain tips (while querying the network for new tips). 

[Note: this is separate from the process of handling gossiped blocks when they do *not* collide with our queries]

(This also wouldn't be a problem if the chain-finding algorithm was sane and included the common root as the first entry of the response).

**Comment by teor2345** [comment]
> (This also wouldn't be a problem if the chain-finding algorithm was sane and included the common root as the first entry of the response).

During initial sync, we could trick peers into providing the common root by making the locator send hashes for `(tip-1), ...` rather than `(tip)`. At least in the typical case.

**Comment by teor2345** [comment]
Turns out that leads to a lot of special cases: we need to track the chain, and we need to handle the genesis block specially.

**Comment by daira** [comment]
> But there is a mitigation we can do. In our sync algorithm we have two phases: (1) "ObtainTips" to get a set of tips to chase down, (2) repeatedly call "ExtendTips" to extend those as far as possible. The unsolicited inv messages have length 1, but when extending tips we expect to get more than one hash.

I don't understand; absolutely nothing stops there from being unsolicited invs with length > 1. I would think that if you don't want to be trying to verify blocks beyond the range you've asked for, you have to ignore them based on their height, not on the length of the inv.

**Comment by hdevalence** [comment]
Yes, nothing stops there from being unsolicited inv messages of larger length, in the same way that nothing stops a peer from replying to a getblocks message maliciously with garbage data. That has to be (and is, albeit as-yet-incompletely) handled elsewhere.

But it's still worthwhile to try to avoid misinterpreting an honest peer's messages, which is what ignoring responses of length 1 does.
