### ISSUE TITLE
Make zebrad work with a small number of peers

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#704]
## TODO

- [ ] Test Zebra with 1 peer, and with 2 peers
  - this bug might have been fixed by #1950 or other zebra-network fixes
- [ ] Fix any issues that come up

## Motivation

I tried configuring zebrad with 2 peers today, and no DNS seeders. It just seemed to hang.

But it seemed to work well with the DNS seeders, and a smaller configured peer set limit (around 5). 

I don't think fixing this issue is a high priority right now. But we might need to fix it for network integration testing.

We might also need to fix it for wallet or exchange support, so users can connect to a single trusted external node.

**Comment by hdevalence** [comment]
This seems like a bug, ideally it would continue to work, although there may be some long delays in request processing at times.  For instance, when crawling the network we send two requests for peers to the network, hoping these will be randomly distributed over the network, but Zcashd behaves badly and silently ignores any requests for peers after the first one, so we have to wait for the request to time out.   IMO this sort of thing is not worth fixing properly (since it would mean writing a bunch of special-purpose code to work around bad Zcashd behavior that we can just ignore in the common case) but the impact should be limited to delays rather than hangs.

Let's dig into this after we get chain verification working.

**Comment by teor2345** [comment]
#1950 might fix this issue, but we need to re-test.

**Comment by teor2345** [comment]
This isn't a supported mode of operation for Zebra, but we do support the 4-8 peers on testnet.
