### ISSUE TITLE
Write unit tests for ObtainTips and ExtendTips

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#730]
While trying to diagnose the genesis block download issue in #725, I noticed that the ObtainTips and ExtendTips implementation in the Syncer doesn't have any unit tests.

We also think that the Syncer follows multiple tips early in the chain sync, which sounds like another bug.

It would be a lot easier to fix these issues if we:
- [ ] refactor the Syncer to separate the network logic and tip-finding logic (if needed)
- [ ] unit test the tip-finding logic

cc @yaahc @hdevalence

**Comment by hdevalence** [comment]
Tests would be helpful, but I think we don't need to refactor the sync code to be able to test it, because it works on a generic (network, verifier, state) tuple, so deterministic testing is possible by plugging in deterministic service impls. We might want to refactor it for other reasons but I think that in principle it should be possible to test as-is.

**Comment by teor2345** [comment]
We need to update the design and add mentorship notes before a volunteer can pick this work up.

**Comment by mpguerra** [comment]
Did we do any of this as part of the mempool work?

**Comment by teor2345** [comment]
> Did we do any of this as part of the mempool work?

No, we didn't modify those parts of the syncer.

**Comment by teor2345** [comment]
These tests got written about a month or two ago.
