### ISSUE TITLE
Check that there are no missing note commitment trees after deduplication

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#7461]
## Motivation

Test that the note commitment tree deduplication format upgrade keeps all unique note commitment trees.

### Possible Design

- Find every height with a tree change
- Check that the number of notes added to that tree equals the number of notes in the transactions of the block at that height

**Comment by teor2345** [comment]
I tested this manually on my local machine. It took 2 hours and 40 minutes on my machine, and timed out at 3 hours in CI:
https://github.com/ZcashFoundation/zebra/pull/7629#issuecomment-1738463244

I don't think it is worth trying to automate this check at this time, because it is not that important.

If it becomes important to do these kinds of checks in future, we could diff a full sync and an updated state at the end of every full sync test. (But we'd have to write that code, too.)
