### ISSUE TITLE
Investigate parallelizing CI steps

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#747]
Branching off from https://github.com/ZcashFoundation/zebra/pull/664#issuecomment-663272765 we've got a couple of improvements we'd like to try making to our CI configuration.

- [ ] run `cargo test --release` as part of CI, though don't require it for merge
- [ ] try to reuse artifacts between GA workflow steps via caching actions or API

**Comment by dconnolly** [comment]
We need to do a `cargo fetch` first, maybe do some caching thing, and either parallelize jobs or steps (I'm not sure if you can parallelize steps, I think the intention is to run jobs in parallel).

https://github.com/actions/cache
https://github.com/actions/cache/blob/main/examples.md#rust---cargo

But in my experience the savings are not from eliminating network time.

Even if we don't do anything clever with caching, running `cargo test` and `cargo build` in parallel and failing fast on either of them could possibly cut that time in half/to the fastest job to fail/longest one to pass.

**Comment by dconnolly** [comment]
In https://github.com/ZcashFoundation/zebra/commit/eda6d86d3e2a9e2efde9207d15cc1fd884800190, I split out the test and build jobs into fully parallel jobs, so of those on our matrix of platforms, the slowest (test|build) on (linux|macos|windows) will be slowest part of our PR builds. Either there is some caching going on or our `cargo fetch`s are just really fast, because those take ~seconds on all those jobs, the expensive parts are the compiling. 

I think this is pretty good, and the config is not excessively complex, it's quite nice.

**Comment by dconnolly** [comment]
I'm going to close this one, and if we feel further need to speed this up etc we can open a more precise issue.
