### ISSUE TITLE
Skip old blocks in periodic state validity checks

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#7645]
## Motivation

Zebra is periodically running the state validity checks in CI, currently every 5 minutes.

The existing state validity checks could be expected to consume non-negligible resources.

### Possible Solution

- Update state validity checks to accept height range
- Track unchecked blocks
- Avoid re-checking parts of state that a running instance of Zebra won't modify

**Comment by teor2345** [comment]
I am concerned that this ticket might look alarming without the necessary context:

> Zebra is periodically running the state validity checks, currently every 5 minutes.

Since PR #7627 was merged yesterday, these periodic checks only happen in CI.

> The existing state validity checks could be expected to consume significant resources.

These checks currently take around 5-10 seconds, and run in parallel. So it might help to clarify what "significant" means here.

> Avoid re-checking immutable parts of state

This is a good constraint, but I think it would help to be more precise about what "immutable" means. For example, if a part of the state can be changed by the newly synced block code, or by any supported upgrade, then it is mutable. (But it would be easy to forget about upgrades changing things.)

**Comment by arya2** [comment]
> So it might help to clarify what "significant" means here.

I had whatever comes after "insignificant" in mind, it's not important but it should be an easy change so it's not totally irrelevant either.

**Comment by teor2345** [comment]
Since this is a high-risk change, and we're only running checks at startup and shutdown in production, I'm going to close this issue.

See my upcoming PR that documents state upgrades for details on the risk, and the cost to diagnose and fix bugs.

**Comment by teor2345** [comment]
Particularly:
- https://github.com/ZcashFoundation/zebra/blob/state-up-doc/book/src/dev/state-db-upgrades.md#writing-blocks-to-the-state
- https://github.com/ZcashFoundation/zebra/blob/state-up-doc/book/src/dev/state-db-upgrades.md#required-tests
