### ISSUE TITLE
Make sure custom user agents conform to BIP-14

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#794]
In #791, we discovered that our default Zcash protocol user agent did not conform to BIP-14:
https://github.com/bitcoin/bips/blob/master/bip-0014.mediawiki

We fixed the issue by changing the default, but the user agent is configurable in zebrad.toml. And that's a useful feature for custom implementations, builds, packaging, or deployments. (BIP-14 user agents exist in a stack, from core to ui.)

TODO:
- [ ] implement a BIP-14 check in zebra-network
- [ ] check the default string is BIP-14 in the zebrad tests
- [ ] ~check the configured string is BIP-14 in the zebrad config load~ (redundant)
- [ ] check the supplied string is BIP-14 in zebra-network

Optionally:
- [ ] reference the BIP format in `zebrad generate` above the relevant config option, and encourage packagers to:
  - append a version string if they re-use a Zebra team build
  - replace the version string if they do their own build

**Comment by hdevalence** [comment]
I think it would be fine to check the user-agent data in `zebra-network` but I don't think that we should check anything while loading the config, because this requires duplicating checks in different places in the codebase.

Even better than checking a supplied string would be changing the config representation to store the parts of a BIP14 user-agent and assembling the final string. Since BIP14 user-agents exist in a stack, perhaps we should put the Zebra user-agent at the root of the stack, and instead have the config specify an (optional) further stack entry.  Do we know what (if any) software in the Zcash ecosystem actually parses BIP14 u-a's?

**Comment by teor2345** [comment]
> Even better than checking a supplied string would be changing the config representation to store the parts of a BIP14 user-agent and assembling the final string.

Sounds good.

> Since BIP14 user-agents exist in a stack, perhaps we should put the Zebra user-agent at the root of the stack, and instead have the config specify an (optional) further stack entry.

This would be a departure from the ECC zcashd build process, which replaces the user agent:
https://github.com/ZcashFoundation/zebra/issues/791#issue-667945031

But it would be similar to btcwire and the zfnd seeders. And it seems like a better design for debugging and analysis.

> Do we know what (if any) software in the Zcash ecosystem actually parses BIP14 u-a's?

zcashd puts them in its logs and RPC fields.

https://blockchair.com/zcash/nodes displays them as node versions, and could use substrings to categorise nodes (but doesn't seem to do so for Zcash).

**Comment by oxarbitrage** [comment]
How can the user agent be changed by config ? I only see it defined as a constant in https://github.com/ZcashFoundation/zebra/blob/main/zebra-network/src/constants.rs#L47 but i was not able to find any place where this value is overwritten by something coming from zebrad.toml.

**Comment by hdevalence** [comment]
Yep, we removed it from the config options in order to prevent this problem. In the future we can add config fields that push data to the BIP14 stack, but I don't think we should try doing that until we have some other users for zebra-network. So I'm going to update the labels on the issue to reflect de-prioritization.

**Comment by dconnolly** [comment]
We don't support custom user agents right now
