### ISSUE TITLE
Make invalid config file error more friendly

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#844]
When the config file has some invalid fields or whatever the error i am getting is:

```
$ ./zebrad start
thread 'main' panicked at 'terminal streams not yet initialized!', /home/oxarbitrage/.cargo/registry/src/github.com-1ecc6299db9ec823/abscissa_core-0.5.2/src/terminal.rs:26:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
$ 
```

**Comment by yaahc** [comment]
I ran into this yesterday and it was caused by the `Terminal` component being constructed twice.

**Comment by yaahc** [comment]
it's almost certainly an issue with the lifecycle on the `Terminal` component, we might need to construct it before loading the config then register it after.

**Comment by hdevalence** [comment]
I think the problem is that we load the config *before* the Terminal, so when we run into an error the terminal isn't initialized.  This was because we wanted to be able to configure the Tracing component, when we were using the Abscissa component.  But now we have our own tracing component so we don't need configuration while we're loading the Abscissa components.

I think the fix is to move
```
        let config = command.process_config(config)?;
        self.config = Some(config);
```
in `application.rs:init()` to after
```
        // Create and register components with the application.
        // We do this first to calculate a proper dependency ordering before
        // application configuration is processed
        self.register_components(command)?;
```
Then we can also get rid of the `self.config = Some(config)` and the `config.take()` lines and just have
```
        self.register_components(command)?;

        let config = command.process_config(config)?;

        self.after_config(config)?;
```

**Comment by hdevalence** [comment]
Oops, this solution wasn't quite right.
