### ISSUE TITLE
Install and run Zcash Block Explorer locally for testing purposes

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#8456]

**Comment by upbqdn** [comment]
We have a fork of Nighthawk's block explorer here: https://github.com/ZcashFoundation/zcash-explorer. I updated the readme with straightforward instructions to run it locally.

**Comment by dismad** [comment]
I would love for this to work with zebrad when all necessary RPC's are built out

**Comment by upbqdn** [comment]
Zaino will most likely be required as well, so it would be better to have integration tests with explorers downstream.

**Comment by upbqdn** [comment]
This issue was created when zebrad was supposed to be the sole backend for explorers.

**Comment by oxarbitrage** [comment]
Let’s give this one more shot before closing and see how far we’ve come. There’s already been some progress toward running the open explorer locally, though I haven’t had a chance to try it yet:

https://github.com/emersonian/zcash-explorer

Since the official explorer now lives in the Zcash organization (https://github.com/zcash/zcash-explorer), we can modify it. I believe it should be possible to adapt it to work with what we have implemented to get started.

**Comment by upbqdn** [comment]
IIRC, the explorer relies on RPCs such as getaddressdeltas, which will be provided by Zaino, and we don't plan to implement them in Zebra currently.

**Comment by zancas** [comment]
Should we reopen this?

**Comment by upbqdn** [comment]
The issue is resolved:

https://github.com/ZcashFoundation/zebra/issues/8456#issuecomment-2228576182


It's possible to run the explorer locally by following the instructions, but only with zcashd.

**Comment by oxarbitrage** [comment]
@upbqdn, I agree, this issue can be closed.

My thought was to let the Explorer serve most pages as-is, but render an error (or a blank page) if a user navigates to a route that depends on an unsupported function. If it turns out we really need those calls, we need to wire the Explorer up to Zaino (and extend Zaino to expose the missing endpoints).

We can track that integration work separately rather than on this issue.

**Comment by upbqdn** [comment]
Yup, it would even be worth having integration tests against the explorer, similar to what we have for lwd. However, given that zebrad will not be enough, the tests might be better suited for the place that will integrate zebrad and zainod.
