### ISSUE TITLE
Add timeouts to the transcript test framework

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#861]
In #610 and #858, we want to turn some existing tests into transcripts. But these tests use timeouts to diagnose deadlocks, and the transcript test framework doesn't support timeouts.

So we want to add timeouts to the transcript test framework.

This is a low-priority task.

**Comment by hdevalence** [comment]
Is there a reason that the transcript service itself has to support timeouts, rather than composing a transcript with a TimeoutLayer (https://docs.rs/tower/0.3.1/tower/timeout/struct.TimeoutLayer.html) ?

**Comment by teor2345** [comment]
I'm not sure.

If we have a timeout on each future, then we can find out the specific await that failed.

If we're just using a TimeoutLayer, then we'll only see the transcript that failed. And we'll have to rely on tracing for further diagnostics. I think that could work.

Let's try the TimeoutLayer, and see if we need any more diagnostics?

(I'm also not sure if we want a timeout on every transcript, or just on specific tests. Let's try specific tests to start with.)

**Comment by hdevalence** [comment]
I think applying a timeout layer to a transcript will actually fail specific requests just like if you were to manually apply a timeout to each future, since that's how [it's implemented internally](https://docs.rs/tower-timeout/0.3.0/src/tower_timeout/lib.rs.html#41-63).  So hopefully it will meet our needs.  If not we can consider adding timeouts but I think that it would be preferable to try composing behavior first.

**Comment by teor2345** [comment]
Ok, I'll close this ticket, and mention TimeoutLayer on the tickets it's blocking.
