### ISSUE TITLE
Add a `nullifiers()` RPC method for getting new nullifier for a block hash or height

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#8621]
## Motivation

We want to provide an alternative to [the lightwalletd methods for getting block nullifiers](https://github.com/zcash/lightwalletd/blob/master/walletrpc/service.proto#L162-L166) in `zebra-rpc` without getting entire blocks.

**Comment by elijahhampton** [comment]
@mpguerra @arya2 Is anyone actively working this ticket?

**Comment by arya2** [comment]
> @mpguerra @arya2 Is anyone actively working this ticket?

Not yet, but we are working on its pre-requisite, https://github.com/ZcashFoundation/zebra/issues/8618.

We could implement this as a method on the JSON-RPC server and copy over the logic to the tonic server once it's available, or branch off of the PR for https://github.com/ZcashFoundation/zebra/issues/8618 once that's open, which should be by tomorrow.

**Comment by nuttycom** [comment]
What might be more useful here is to be able to get the "nullifier map" that the wallets need in order to be able to detect the spends of their notes. Ideally this would be segmented in some fashion, such that newer wallets need to download less data than old ones, and the representation could be either (ideally) as a compressed map from nullifier (or a prefix of the nullifier) to block height- maybe using https://github.com/bitwiseshiftleft/compressed_map, or simply as a series of bloom filters, where each filter corresponds to some block range. In either case, false-positive detection of spends is fine, since the wallet will be prioritizing the trial decryption of those blocks anyway.

With the nullifier map approach, it becomes possible for wallets to detect exactly where their notes are spent; with a series of bloom filters, you only can detect what block range the note is spent in. But the compressed map implementation linked above is characterized as "research-grade" software, so for pragmatic reasons using a mature bloom filter implementation might be better. For that approach, it might make sense for each bloom filter to correspond to a 2^16 note commitment tree subtree, or perhaps 2^15 or 2^14 if we want finer granularity.

**Comment by elijahhampton** [comment]
Is this ticket still blocked due to #8618 or pending conversations around the implementation of bloom filters/nullifier map?  If not, I can open a PR for the nullifier RPC method.

**Comment by nuttycom** [comment]
> Is this ticket still blocked due to #8618 or pending conversations around the implementation of bloom filters/nullifier map? If not, I can open a PR for the nullifier RPC method.

I don't think that the existing design of this RPC method is useful, that's why I think we need to go with a nullfier map or bloom filter approach.

**Comment by arya2** [comment]
This RPC method is not currently used or required, we need a separate issue for @nuttycom's idea.
