### ISSUE TITLE
feature: `getrawtransaction` output should match `zcashd`

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#8646]
### Motivation

In order for `zebrad` to be able to act as a drop in replacement for `zcashd` we should ensure that the Zebra output for the `getrawtransaction` RPC call matches the `zcashd` output.

This was [reported by a user in Discord](https://discord.com/channels/809218587167293450/809251029673312267/1255330728292651138).

### Related Work

#8645

**Comment by upbqdn** [comment]
I didn't manage to figure out what the desired output should be from the issue description. Zebra returns only a subset of what `zcashd` returns, but the returned data matches `zcashd` in all checks. The reduced output is due to tight scope. Closing until we figure out what we need to add or change.
