### ISSUE TITLE
Set the NU6 testnet activation height and network protocol version

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#8689]
### Motivation

We need to update the consensus parameters for NU6 testnet.

### Specifications

TBD: (We need to wait for the relevant NU6 deployment ZIP)

### Related Work

#4115
#8681
depends-on:  zcash/zips#878
depends-on:  zcash/librustzcash#1454

**Comment by oxarbitrage** [comment]
https://github.com/zcash/zips/pull/878

**Comment by oxarbitrage** [comment]
This issue is straightforward to do but it is blocked by several reasons:

- The ZIP with the info we want to add is a draft: https://github.com/zcash/zips/pull/878
- `zcash_primitives` need to have `Nu6` data: https://github.com/zcash/librustzcash/pull/1454

Assuming we can have stable Nu6 in the next `zcash_primitives` release, we also need:
- Deal with the release breaking changes and upgrade Zebra before adding the constant values.

**Comment by arya2** [comment]
`CURRENT_NETWORK_PROTOCOL_VERSION` needs to be bumped to `170_110` too so that [peer candidates won't reject Zebra after NU6 is active](https://github.com/ZcashFoundation/zebra/blob/restore-internal-miner/zebra-network/src/peer/handshake.rs#L672).

We also need to set the Testnet activation height, this issue was closed mistakenly.

**Comment by mpguerra** [comment]
this is now done
