### ISSUE TITLE
Support hostnames in the zebrad listener configs

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#948]
zebrad's config uses `SocketAddr` for the Zcash, metrics, and tracing listeners. `SocketAddr` only accepts IP address literals, and does not do DNS resolution on hostnames.

If we make zebrad support hostnames, then users can configure dynamic IP addresses, and generic addresses like `localhost`.

Here's how we can make this change:
- [ ] change the listener configs to a string
- [ ] parse the string using `ToSocketAddrs`: https://doc.rust-lang.org/stable/std/net/trait.ToSocketAddrs.html#tymethod.to_socket_addrs
- [ ] use the first address returned by DNS
- [ ] fail if there are no addresses, with a helpful error message
- [ ] add zebrad acceptance tests for each type of address:
  - [ ] hostnames (localhost)
  - [ ] IPv4 literals (127.0.0.1)
  - [ ] IPv6 literals (::1)
  - [ ] No address - optional listeners only: the zcash listener is required

As an extra feature, we could bind each listener to all returned addresses, and listen on them simultaneously. But that should happen in a separate commit or PR, once we have working code and tests.

**Comment by dconnolly** [comment]
I like this 👍

**Comment by oxarbitrage** [comment]
I am going to be working on this one.

**Comment by hdevalence** [comment]
branching off of https://github.com/ZcashFoundation/zebra/pull/951#discussion_r480307498, it looks like this feature adds quite a lot of additional complexity, both in terms of the code required to implement it as well as in terms of the additional program states. Before, we could parse the config with no extra steps, and after parsing we'd have a valid address, but now we have to have additional error-handling logic and we have a more complicated state machine, because we now need to handle network timeouts when parsing our config, and connectivity issues can interfere in new and unexpected places (as in that discussion).

In contrast, the ergonomic benefit this provides seems rather small to me. I think that this points away from implementing this feature and towards keeping the existing, simpler configuration data.

**Comment by teor2345** [comment]
I think you're right, it seems like a really complicated feature to implement. Based on my previous dev experience, it can also be surprising to users that the hostname is resolved once on startup, rather than dynamically changing as DNS changes.

Here's how we could move forward:
* document that zebrad only accepts IP addresses
* document a workaround for hostnames: resolve hostnames using an external tool, which can restart zebra if the IP address has changed. (Or on a schedule set by the user.)
* as related future work, allow users to configure multiple Zcash listeners - but we should wait until there is an actual need for this feature - users can use a port redirector / firewall in the meantime

**Comment by teor2345** [comment]
Blocked pending a decision on the design.

We can separate out the test parts of the PR, and commit them, because they are still useful:

add zebrad acceptance tests for each type of address: 
- [ ] IPv4 literals (127.0.0.1)
- [ ] IPv6 literals (::1)
- [ ] No address - optional listeners only: the zcash listener is required

**Comment by teor2345** [comment]
We decided not to do this - the remaining work is testing optional listeners on IP addresses in #995.
