### ISSUE TITLE
Rename `zebra_state::on_disk`

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#975]
In #974, we removed the in-memory state implementation. That leaves us with only one state implementation, which is called `on_disk`.

Since #896 merged, `on_disk` has been an incorrect name, because ephemeral states are in memory on Linux. It's also a confusing name when it appears in external import paths.

Let's rename it to `sled`, or something similar, and make it private to `zebra_state`.

Let's also re-export `on_disk::init` from the root of `zebra_state`, and use it as `zebra_state::init`. That way, we don't leak implementation details into dependent crates.

**Comment by hdevalence** [comment]
As part of #974 the entire module was made private, so this change and other changes can be made without interfering with the external API.

Another thing to consider while doing this restructuring work is whether we should split out the request, response, etc types into separate files and re-export them from `lib.rs` to keep the `lib.rs` tidy.  It might also make sense to split up the `on_disk` module into different components, rather than just renaming it to `sled`.

**Comment by hdevalence** [comment]
This is going to be a large change, and it will block and be blocked on any other changes to the state system.  We should make sure to do it **before** starting implementation work on #902, because it will be much more work to do afterwards. (cc @ZcashFoundation/zebra-team )
